using DataAccessLibrary.logic;
using System.Text.Json;

namespace DataAccessLibrary;
public class SQLite_setup
{
    /// <summary>
    /// Standard setup data and database tables needed for projectB to run (Tables, 3 x Room + Seats)
    /// </summary>
    /// <param name="databasePath"></param>
    public static void SetupProjectB(RoomFactory rf, MovieFactory mf, string JSONPath)
    {
        //----- Setting up JSON file for password -----//
        string fileName = "Medewerker.json";
        if (!File.Exists(JSONPath + "\\" + fileName))
        {
            
            string jsonString = JsonSerializer.Serialize(new KeyValuePair<string, string>("PassWord", "w817"));
            File.WriteAllText(JSONPath + "\\" + fileName, jsonString);
        }
        

        if (rf.GetItemFromId(1) == null)
        {
            //Row widths Layouts
            List<int> RowWidthsLayouts = new List<int> { 12, 18, 30 };

            //Capacities Layouts
            List<int> capacitiesLayouts = new List<int> { 168, 342, 600 };

            //New rooms creation
            RoomModel Room1 = new RoomModel($"Room1", 168, 12);
            RoomModel Room2 = new RoomModel($"Room2", 342, 18);
            RoomModel Room3 = new RoomModel($"Room3", 600, 30);

            SeatModel[] layout1 = new SeatModel[] {
                    new SeatModel("0", " ", " ", Room1),
                    new SeatModel("1", " ", " ", Room1),
                    new SeatModel("2", "1", "Normaal", Room1),
                    new SeatModel("3", "1", "Normaal", Room1),
                    new SeatModel("4", "1", "Normaal", Room1),
                    new SeatModel("5", "1", "Normaal", Room1),
                    new SeatModel("6", "1", "Normaal", Room1),
                    new SeatModel("7", "1", "Normaal", Room1),
                    new SeatModel("8", "1", "Normaal", Room1),
                    new SeatModel("9", "1", "Normaal", Room1),
                    new SeatModel("10", " ", " ", Room1),
                    new SeatModel("11", " ", " ", Room1),
                    new SeatModel("12", " ", " ", Room1),
                    new SeatModel("13", " ", " ", Room1),
                    new SeatModel("14", "1", "Normaal", Room1),
                    new SeatModel("15", "1", "Normaal", Room1),
                    new SeatModel("16", "1", "Normaal", Room1),
                    new SeatModel("17", "1", "Normaal", Room1),
                    new SeatModel("18", "1", "Normaal", Room1),
                    new SeatModel("19", "1", "Normaal", Room1),
                    new SeatModel("20", "1", "Normaal", Room1),
                    new SeatModel("21", "1", "Normaal", Room1),
                    new SeatModel("22", " ", " ", Room1),
                    new SeatModel("23", " ", " ", Room1),
                    new SeatModel("24", " ", " ", Room1),
                    new SeatModel("25", "1", "Normaal", Room1),
                    new SeatModel("26", "1", "Normaal", Room1),
                    new SeatModel("27", "1", "Normaal", Room1),
                    new SeatModel("28", "1", "Normaal", Room1),
                    new SeatModel("29", "1", "Normaal", Room1),
                    new SeatModel("30", "1", "Normaal", Room1),
                    new SeatModel("31", "1", "Normaal", Room1),
                    new SeatModel("32", "1", "Normaal", Room1),
                    new SeatModel("33", "1", "Normaal", Room1),
                    new SeatModel("34", "1", "Normaal", Room1),
                    new SeatModel("35", " ", " ", Room1),
                    new SeatModel("36", "1", "Normaal", Room1),
                    new SeatModel("37", "1", "Normaal", Room1),
                    new SeatModel("38", "1", "Normaal", Room1),
                    new SeatModel("39", "1", "Normaal", Room1),
                    new SeatModel("40", "1", "Normaal", Room1),
                    new SeatModel("41", "2", "Extra Beenruimte", Room1),
                    new SeatModel("42", "2", "Extra Beenruimte", Room1),
                    new SeatModel("43", "1", "Normaal", Room1),
                    new SeatModel("44", "1", "Normaal", Room1),
                    new SeatModel("45", "1", "Normaal", Room1),
                    new SeatModel("46", "1", "Normaal", Room1),
                    new SeatModel("47", "1", "Normaal", Room1),
                    new SeatModel("48", "1", "Normaal", Room1),
                    new SeatModel("49", "1", "Normaal", Room1),
                    new SeatModel("50", "1", "Normaal", Room1),
                    new SeatModel("51", "1", "Normaal", Room1),
                    new SeatModel("52", "2", "Extra Beenruimte", Room1),
                    new SeatModel("53", "2", "Extra Beenruimte", Room1),
                    new SeatModel("54", "2", "Extra Beenruimte", Room1),
                    new SeatModel("55", "2", "Extra Beenruimte", Room1),
                    new SeatModel("56", "1", "Normaal", Room1),
                    new SeatModel("57", "1", "Normaal", Room1),
                    new SeatModel("58", "1", "Normaal", Room1),
                    new SeatModel("59", "1", "Normaal", Room1),
                    new SeatModel("60", "1", "Normaal", Room1),
                    new SeatModel("61", "1", "Normaal", Room1),
                    new SeatModel("62", "1", "Normaal", Room1),
                    new SeatModel("63", "2", "Extra Beenruimte", Room1),
                    new SeatModel("64", "2", "Extra Beenruimte", Room1),
                    new SeatModel("65", "3", "Love SeatModel", Room1),
                    new SeatModel("66", "3", "Love SeatModel", Room1),
                    new SeatModel("67", "2", "Extra Beenruimte", Room1),
                    new SeatModel("68", "2", "Extra Beenruimte", Room1),
                    new SeatModel("69", "1", "Normaal", Room1),
                    new SeatModel("70", "1", "Normaal", Room1),
                    new SeatModel("71", "1", "Normaal", Room1),
                    new SeatModel("72", "1", "Normaal", Room1),
                    new SeatModel("73", "1", "Normaal", Room1),
                    new SeatModel("74", "1", "Normaal", Room1),
                    new SeatModel("75", "2", "Extra Beenruimte", Room1),
                    new SeatModel("76", "2", "Extra Beenruimte", Room1),
                    new SeatModel("77", "3", "Love SeatModel", Room1),
                    new SeatModel("78", "3", "Love SeatModel", Room1),
                    new SeatModel("79", "2", "Extra Beenruimte", Room1),
                    new SeatModel("80", "2", "Extra Beenruimte", Room1),
                    new SeatModel("81", "1", "Normaal", Room1),
                    new SeatModel("82", "1", "Normaal", Room1),
                    new SeatModel("83", "1", "Normaal", Room1),
                    new SeatModel("84", "1", "Normaal", Room1),
                    new SeatModel("85", "1", "Normaal", Room1),
                    new SeatModel("86", "1", "Normaal", Room1),
                    new SeatModel("87", "2", "Extra Beenruimte", Room1),
                    new SeatModel("88", "2", "Extra Beenruimte", Room1),
                    new SeatModel("89", "3", "Love SeatModel", Room1),
                    new SeatModel("90", "3", "Love SeatModel", Room1),
                    new SeatModel("91", "2", "Extra Beenruimte", Room1),
                    new SeatModel("92", "2", "Extra Beenruimte", Room1),
                    new SeatModel("93", "1", "Normaal", Room1),
                    new SeatModel("94", "1", "Normaal", Room1),
                    new SeatModel("95", "1", "Normaal", Room1),
                    new SeatModel("96", "1", "Normaal", Room1),
                    new SeatModel("97", "1", "Normaal", Room1),
                    new SeatModel("98", "1", "Normaal", Room1),
                    new SeatModel("99", "2", "Extra Beenruimte", Room1),
                    new SeatModel("100", "2", "Extra Beenruimte", Room1),
                    new SeatModel("101", "3", "Love SeatModel", Room1),
                    new SeatModel("102", "3", "Love SeatModel", Room1),
                    new SeatModel("103", "2", "Extra Beenruimte", Room1),
                    new SeatModel("104", "2", "Extra Beenruimte", Room1),
                    new SeatModel("105", "1", "Normaal", Room1),
                    new SeatModel("106", "1", "Normaal", Room1),
                    new SeatModel("107", "1", "Normaal", Room1),
                    new SeatModel("108", "1", "Normaal", Room1),
                    new SeatModel("109", "1", "Normaal", Room1),
                    new SeatModel("110", "1", "Normaal", Room1),
                    new SeatModel("111", "1", "Normaal", Room1),
                    new SeatModel("112", "2", "Extra Beenruimte", Room1),
                    new SeatModel("113", "2", "Extra Beenruimte", Room1),
                    new SeatModel("114", "2", "Extra Beenruimte", Room1),
                    new SeatModel("115", "2", "Extra Beenruimte", Room1),
                    new SeatModel("116", "1", "Normaal", Room1),
                    new SeatModel("117", "1", "Normaal", Room1),
                    new SeatModel("118", "1", "Normaal", Room1),
                    new SeatModel("119", "1", "Normaal", Room1),
                    new SeatModel("120", "1", "Normaal", Room1),
                    new SeatModel("121", "1", "Normaal", Room1),
                    new SeatModel("122", "1", "Normaal", Room1),
                    new SeatModel("123", "1", "Normaal", Room1),
                    new SeatModel("124", "1", "Normaal", Room1),
                    new SeatModel("125", "2", "Extra Beenruimte", Room1),
                    new SeatModel("126", "2", "Extra Beenruimte", Room1),
                    new SeatModel("127", "1", "Normaal", Room1),
                    new SeatModel("128", "1", "Normaal", Room1),
                    new SeatModel("129", "1", "Normaal", Room1),
                    new SeatModel("130", "1", "Normaal", Room1),
                    new SeatModel("131", "1", "Normaal", Room1),
                    new SeatModel("132", " ", " ", Room1),
                    new SeatModel("133", "1", "Normaal", Room1),
                    new SeatModel("134", "1", "Normaal", Room1),
                    new SeatModel("135", "1", "Normaal", Room1),
                    new SeatModel("136", "1", "Normaal", Room1),
                    new SeatModel("137", "1", "Normaal", Room1),
                    new SeatModel("138", "1", "Normaal", Room1),
                    new SeatModel("139", "1", "Normaal", Room1),
                    new SeatModel("140", "1", "Normaal", Room1),
                    new SeatModel("141", "1", "Normaal", Room1),
                    new SeatModel("142", "1", "Normaal", Room1),
                    new SeatModel("143", " ", " ", Room1),
                    new SeatModel("144", " ", " ", Room1),
                    new SeatModel("145", "1", "Normaal", Room1),
                    new SeatModel("146", "1", "Normaal", Room1),
                    new SeatModel("147", "1", "Normaal", Room1),
                    new SeatModel("148", "1", "Normaal", Room1),
                    new SeatModel("149", "1", "Normaal", Room1),
                    new SeatModel("150", "1", "Normaal", Room1),
                    new SeatModel("151", "1", "Normaal", Room1),
                    new SeatModel("152", "1", "Normaal", Room1),
                    new SeatModel("153", "1", "Normaal", Room1),
                    new SeatModel("154", "1", "Normaal", Room1),
                    new SeatModel("155", " ", " ", Room1),
                    new SeatModel("156", " ", " ", Room1),
                    new SeatModel("157", " ", " ", Room1),
                    new SeatModel("158", "1", "Normaal", Room1),
                    new SeatModel("159", "1", "Normaal", Room1),
                    new SeatModel("160", "1", "Normaal", Room1),
                    new SeatModel("161", "1", "Normaal", Room1),
                    new SeatModel("162", "1", "Normaal", Room1),
                    new SeatModel("163", "1", "Normaal", Room1),
                    new SeatModel("164", "1", "Normaal", Room1),
                    new SeatModel("165", "1", "Normaal", Room1),
                    new SeatModel("166", " ", " ", Room1),
                    new SeatModel("167", " ", " ", Room1)
            };
            SeatModel[] layout2 = new SeatModel[] {
                    new SeatModel("0", " ", " ", Room2),
                    new SeatModel("1", " ", " ", Room2),
                    new SeatModel("2", " ", " ", Room2),
                    new SeatModel("3", "1", "Normaal", Room2),
                    new SeatModel("4", "1", "Normaal", Room2),
                    new SeatModel("5", "1", "Normaal", Room2),
                    new SeatModel("6", "1", "Normaal", Room2),
                    new SeatModel("7", "1", "Normaal", Room2),
                    new SeatModel("8", "1", "Normaal", Room2),
                    new SeatModel("9", "1", "Normaal", Room2),
                    new SeatModel("10", "1", "Normaal", Room2),
                    new SeatModel("11", "1", "Normaal", Room2),
                    new SeatModel("12", "1", "Normaal", Room2),
                    new SeatModel("13", "1", "Normaal", Room2),
                    new SeatModel("14", "1", "Normaal", Room2),
                    new SeatModel("15", " ", " ", Room2),
                    new SeatModel("16", " ", " ", Room2),
                    new SeatModel("17", " ", " ", Room2),
                    new SeatModel("18", " ", " ", Room2),
                    new SeatModel("19", " ", " ", Room2),
                    new SeatModel("20", " ", " ", Room2),
                    new SeatModel("21", "1", "Normaal", Room2),
                    new SeatModel("22", "1", "Normaal", Room2),
                    new SeatModel("23", "1", "Normaal", Room2),
                    new SeatModel("24", "1", "Normaal", Room2),
                    new SeatModel("25", "1", "Normaal", Room2),
                    new SeatModel("26", "1", "Normaal", Room2),
                    new SeatModel("27", "1", "Normaal", Room2),
                    new SeatModel("28", "1", "Normaal", Room2),
                    new SeatModel("29", "1", "Normaal", Room2),
                    new SeatModel("30", "1", "Normaal", Room2),
                    new SeatModel("31", "1", "Normaal", Room2),
                    new SeatModel("32", "1", "Normaal", Room2),
                    new SeatModel("33", " ", " ", Room2),
                    new SeatModel("34", " ", " ", Room2),
                    new SeatModel("35", " ", " ", Room2),
                    new SeatModel("36", " ", " ", Room2),
                    new SeatModel("37", " ", " ", Room2),
                    new SeatModel("38", "1", "Normaal", Room2),
                    new SeatModel("39", "1", "Normaal", Room2),
                    new SeatModel("40", "1", "Normaal", Room2),
                    new SeatModel("41", "1", "Normaal", Room2),
                    new SeatModel("42", "1", "Normaal", Room2),
                    new SeatModel("43", "1", "Normaal", Room2),
                    new SeatModel("44", "1", "Normaal", Room2),
                    new SeatModel("45", "1", "Normaal", Room2),
                    new SeatModel("46", "1", "Normaal", Room2),
                    new SeatModel("47", "1", "Normaal", Room2),
                    new SeatModel("48", "1", "Normaal", Room2),
                    new SeatModel("49", "1", "Normaal", Room2),
                    new SeatModel("50", "1", "Normaal", Room2),
                    new SeatModel("51", "1", "Normaal", Room2),
                    new SeatModel("52", " ", " ", Room2),
                    new SeatModel("53", " ", " ", Room2),
                    new SeatModel("54", " ", " ", Room2),
                    new SeatModel("55", " ", " ", Room2),
                    new SeatModel("56", "1", "Normaal", Room2),
                    new SeatModel("57", "1", "Normaal", Room2),
                    new SeatModel("58", "1", "Normaal", Room2),
                    new SeatModel("59", "1", "Normaal", Room2),
                    new SeatModel("60", "2", "Extra Beenruimte", Room2),
                    new SeatModel("61", "2", "Extra Beenruimte", Room2),
                    new SeatModel("62", "2", "Extra Beenruimte", Room2),
                    new SeatModel("63", "2", "Extra Beenruimte", Room2),
                    new SeatModel("64", "2", "Extra Beenruimte", Room2),
                    new SeatModel("65", "2", "Extra Beenruimte", Room2),
                    new SeatModel("66", "1", "Normaal", Room2),
                    new SeatModel("67", "1", "Normaal", Room2),
                    new SeatModel("68", "1", "Normaal", Room2),
                    new SeatModel("69", "1", "Normaal", Room2),
                    new SeatModel("70", " ", " ", Room2),
                    new SeatModel("71", " ", " ", Room2),
                    new SeatModel("72", " ", " ", Room2),
                    new SeatModel("73", " ", " ", Room2),
                    new SeatModel("74", "1", "Normaal", Room2),
                    new SeatModel("75", "1", "Normaal", Room2),
                    new SeatModel("76", "1", "Normaal", Room2),
                    new SeatModel("77", "1", "Normaal", Room2),
                    new SeatModel("78", "2", "Extra Beenruimte", Room2),
                    new SeatModel("79", "2", "Extra Beenruimte", Room2),
                    new SeatModel("80", "2", "Extra Beenruimte", Room2),
                    new SeatModel("81", "2", "Extra Beenruimte", Room2),
                    new SeatModel("82", "2", "Extra Beenruimte", Room2),
                    new SeatModel("83", "2", "Extra Beenruimte", Room2),
                    new SeatModel("84", "1", "Normaal", Room2),
                    new SeatModel("85", "1", "Normaal", Room2),
                    new SeatModel("86", "1", "Normaal", Room2),
                    new SeatModel("87", "1", "Normaal", Room2),
                    new SeatModel("88", " ", " ", Room2),
                    new SeatModel("89", " ", " ", Room2),
                    new SeatModel("90", " ", " ", Room2),
                    new SeatModel("91", "1", "Normaal", Room2),
                    new SeatModel("92", "1", "Normaal", Room2),
                    new SeatModel("93", "1", "Normaal", Room2),
                    new SeatModel("94", "1", "Normaal", Room2),
                    new SeatModel("95", "2", "Extra Beenruimte", Room2),
                    new SeatModel("96", "2", "Extra Beenruimte", Room2),
                    new SeatModel("97", "2", "Extra Beenruimte", Room2),
                    new SeatModel("98", "2", "Extra Beenruimte", Room2),
                    new SeatModel("99", "2", "Extra Beenruimte", Room2),
                    new SeatModel("100", "2", "Extra Beenruimte", Room2),
                    new SeatModel("101", "2", "Extra Beenruimte", Room2),
                    new SeatModel("102", "2", "Extra Beenruimte", Room2),
                    new SeatModel("103", "1", "Normaal", Room2),
                    new SeatModel("104", "1", "Normaal", Room2),
                    new SeatModel("105", "1", "Normaal", Room2),
                    new SeatModel("106", "1", "Normaal", Room2),
                    new SeatModel("107", " ", " ", Room2),
                    new SeatModel("108", " ", " ", Room2),
                    new SeatModel("109", "1", "Normaal", Room2),
                    new SeatModel("110", "1", "Normaal", Room2),
                    new SeatModel("111", "1", "Normaal", Room2),
                    new SeatModel("112", "2", "Extra Beenruimte", Room2),
                    new SeatModel("113", "2", "Extra Beenruimte", Room2),
                    new SeatModel("114", "2", "Extra Beenruimte", Room2),
                    new SeatModel("115", "2", "Extra Beenruimte", Room2),
                    new SeatModel("116", "3", "Love SeatModel", Room2),
                    new SeatModel("117", "3", "Love SeatModel", Room2),
                    new SeatModel("118", "2", "Extra Beenruimte", Room2),
                    new SeatModel("119", "2", "Extra Beenruimte", Room2),
                    new SeatModel("120", "2", "Extra Beenruimte", Room2),
                    new SeatModel("121", "2", "Extra Beenruimte", Room2),
                    new SeatModel("122", "1", "Normaal", Room2),
                    new SeatModel("123", "1", "Normaal", Room2),
                    new SeatModel("124", "1", "Normaal", Room2),
                    new SeatModel("125", " ", " ", Room2),
                    new SeatModel("126", " ", " ", Room2),
                    new SeatModel("127", "1", "Normaal", Room2),
                    new SeatModel("128", "1", "Normaal", Room2),
                    new SeatModel("129", "2", "Extra Beenruimte", Room2),
                    new SeatModel("130", "2", "Extra Beenruimte", Room2),
                    new SeatModel("131", "2", "Extra Beenruimte", Room2),
                    new SeatModel("132", "2", "Extra Beenruimte", Room2),
                    new SeatModel("133", "3", "Love SeatModel", Room2),
                    new SeatModel("134", "3", "Love SeatModel", Room2),
                    new SeatModel("135", "3", "Love SeatModel", Room2),
                    new SeatModel("136", "3", "Love SeatModel", Room2),
                    new SeatModel("137", "2", "Extra Beenruimte", Room2),
                    new SeatModel("138", "2", "Extra Beenruimte", Room2),
                    new SeatModel("139", "2", "Extra Beenruimte", Room2),
                    new SeatModel("140", "2", "Extra Beenruimte", Room2),
                    new SeatModel("141", "1", "Normaal", Room2),
                    new SeatModel("142", "1", "Normaal", Room2),
                    new SeatModel("143", " ", " ", Room2),
                    new SeatModel("144", "1", "Normaal", Room2),
                    new SeatModel("145", "1", "Normaal", Room2),
                    new SeatModel("146", "2", "Extra Beenruimte", Room2),
                    new SeatModel("147", "2", "Extra Beenruimte", Room2),
                    new SeatModel("148", "2", "Extra Beenruimte", Room2),
                    new SeatModel("149", "2", "Extra Beenruimte", Room2),
                    new SeatModel("150", "3", "Love SeatModel", Room2),
                    new SeatModel("151", "3", "Love SeatModel", Room2),
                    new SeatModel("152", "3", "Love SeatModel", Room2),
                    new SeatModel("153", "3", "Love SeatModel", Room2),
                    new SeatModel("154", "3", "Love SeatModel", Room2),
                    new SeatModel("155", "3", "Love SeatModel", Room2),
                    new SeatModel("156", "2", "Extra Beenruimte", Room2),
                    new SeatModel("157", "2", "Extra Beenruimte", Room2),
                    new SeatModel("158", "2", "Extra Beenruimte", Room2),
                    new SeatModel("159", "2", "Extra Beenruimte", Room2),
                    new SeatModel("160", "1", "Normaal", Room2),
                    new SeatModel("161", "1", "Normaal", Room2),
                    new SeatModel("162", "1", "Normaal", Room2),
                    new SeatModel("163", "1", "Normaal", Room2),
                    new SeatModel("164", "2", "Extra Beenruimte", Room2),
                    new SeatModel("165", "2", "Extra Beenruimte", Room2),
                    new SeatModel("166", "2", "Extra Beenruimte", Room2),
                    new SeatModel("167", "2", "Extra Beenruimte", Room2),
                    new SeatModel("168", "3", "Love SeatModel", Room2),
                    new SeatModel("169", "3", "Love SeatModel", Room2),
                    new SeatModel("170", "3", "Love SeatModel", Room2),
                    new SeatModel("171", "3", "Love SeatModel", Room2),
                    new SeatModel("172", "3", "Love SeatModel", Room2),
                    new SeatModel("173", "3", "Love SeatModel", Room2),
                    new SeatModel("174", "2", "Extra Beenruimte", Room2),
                    new SeatModel("175", "2", "Extra Beenruimte", Room2),
                    new SeatModel("176", "2", "Extra Beenruimte", Room2),
                    new SeatModel("177", "2", "Extra Beenruimte", Room2),
                    new SeatModel("178", "1", "Normaal", Room2),
                    new SeatModel("179", "1", "Normaal", Room2),
                    new SeatModel("180", "1", "Normaal", Room2),
                    new SeatModel("181", "1", "Normaal", Room2),
                    new SeatModel("182", "2", "Extra Beenruimte", Room2),
                    new SeatModel("183", "2", "Extra Beenruimte", Room2),
                    new SeatModel("184", "2", "Extra Beenruimte", Room2),
                    new SeatModel("185", "2", "Extra Beenruimte", Room2),
                    new SeatModel("186", "3", "Love SeatModel", Room2),
                    new SeatModel("187", "3", "Love SeatModel", Room2),
                    new SeatModel("188", "3", "Love SeatModel", Room2),
                    new SeatModel("189", "3", "Love SeatModel", Room2),
                    new SeatModel("190", "3", "Love SeatModel", Room2),
                    new SeatModel("191", "3", "Love SeatModel", Room2),
                    new SeatModel("192", "2", "Extra Beenruimte", Room2),
                    new SeatModel("193", "2", "Extra Beenruimte", Room2),
                    new SeatModel("194", "2", "Extra Beenruimte", Room2),
                    new SeatModel("195", "2", "Extra Beenruimte", Room2),
                    new SeatModel("196", "1", "Normaal", Room2),
                    new SeatModel("197", "1", "Normaal", Room2),
                    new SeatModel("198", "1", "Normaal", Room2),
                    new SeatModel("199", "1", "Normaal", Room2),
                    new SeatModel("200", "1", "Normaal", Room2),
                    new SeatModel("201", "2", "Extra Beenruimte", Room2),
                    new SeatModel("202", "2", "Extra Beenruimte", Room2),
                    new SeatModel("203", "2", "Extra Beenruimte", Room2),
                    new SeatModel("204", "3", "Love SeatModel", Room2),
                    new SeatModel("205", "3", "Love SeatModel", Room2),
                    new SeatModel("206", "3", "Love SeatModel", Room2),
                    new SeatModel("207", "3", "Love SeatModel", Room2),
                    new SeatModel("208", "3", "Love SeatModel", Room2),
                    new SeatModel("209", "3", "Love SeatModel", Room2),
                    new SeatModel("210", "2", "Extra Beenruimte", Room2),
                    new SeatModel("211", "2", "Extra Beenruimte", Room2),
                    new SeatModel("212", "2", "Extra Beenruimte", Room2),
                    new SeatModel("213", "1", "Normaal", Room2),
                    new SeatModel("214", "1", "Normaal", Room2),
                    new SeatModel("215", "1", "Normaal", Room2),
                    new SeatModel("216", "1", "Normaal", Room2),
                    new SeatModel("217", "1", "Normaal", Room2),
                    new SeatModel("218", "1", "Normaal", Room2),
                    new SeatModel("219", "2", "Extra Beenruimte", Room2),
                    new SeatModel("220", "2", "Extra Beenruimte", Room2),
                    new SeatModel("221", "2", "Extra Beenruimte", Room2),
                    new SeatModel("222", "2", "Extra Beenruimte", Room2),
                    new SeatModel("223", "3", "Love SeatModel", Room2),
                    new SeatModel("224", "3", "Love SeatModel", Room2),
                    new SeatModel("225", "3", "Love SeatModel", Room2),
                    new SeatModel("226", "3", "Love SeatModel", Room2),
                    new SeatModel("227", "2", "Extra Beenruimte", Room2),
                    new SeatModel("228", "2", "Extra Beenruimte", Room2),
                    new SeatModel("229", "2", "Extra Beenruimte", Room2),
                    new SeatModel("230", "2", "Extra Beenruimte", Room2),
                    new SeatModel("231", "1", "Normaal", Room2),
                    new SeatModel("232", "1", "Normaal", Room2),
                    new SeatModel("233", "1", "Normaal", Room2),
                    new SeatModel("234", " ", " ", Room2),
                    new SeatModel("235", "1", "Normaal", Room2),
                    new SeatModel("236", "1", "Normaal", Room2),
                    new SeatModel("237", "1", "Normaal", Room2),
                    new SeatModel("238", "2", "Extra Beenruimte", Room2),
                    new SeatModel("239", "2", "Extra Beenruimte", Room2),
                    new SeatModel("240", "2", "Extra Beenruimte", Room2),
                    new SeatModel("241", "2", "Extra Beenruimte", Room2),
                    new SeatModel("242", "3", "Love SeatModel", Room2),
                    new SeatModel("243", "3", "Love SeatModel", Room2),
                    new SeatModel("244", "2", "Extra Beenruimte", Room2),
                    new SeatModel("245", "2", "Extra Beenruimte", Room2),
                    new SeatModel("246", "2", "Extra Beenruimte", Room2),
                    new SeatModel("247", "2", "Extra Beenruimte", Room2),
                    new SeatModel("248", "1", "Normaal", Room2),
                    new SeatModel("249", "1", "Normaal", Room2),
                    new SeatModel("250", "1", "Normaal", Room2),
                    new SeatModel("251", " ", " ", Room2),
                    new SeatModel("252", " ", " ", Room2),
                    new SeatModel("253", "1", "Normaal", Room2),
                    new SeatModel("254", "1", "Normaal", Room2),
                    new SeatModel("255", "1", "Normaal", Room2),
                    new SeatModel("256", "2", "Extra Beenruimte", Room2),
                    new SeatModel("257", "2", "Extra Beenruimte", Room2),
                    new SeatModel("258", "2", "Extra Beenruimte", Room2),
                    new SeatModel("259", "2", "Extra Beenruimte", Room2),
                    new SeatModel("260", "2", "Extra Beenruimte", Room2),
                    new SeatModel("261", "2", "Extra Beenruimte", Room2),
                    new SeatModel("262", "2", "Extra Beenruimte", Room2),
                    new SeatModel("263", "2", "Extra Beenruimte", Room2),
                    new SeatModel("264", "2", "Extra Beenruimte", Room2),
                    new SeatModel("265", "2", "Extra Beenruimte", Room2),
                    new SeatModel("266", "1", "Normaal", Room2),
                    new SeatModel("267", "1", "Normaal", Room2),
                    new SeatModel("268", "1", "Normaal", Room2),
                    new SeatModel("269", " ", " ", Room2),
                    new SeatModel("270", " ", " ", Room2),
                    new SeatModel("271", "1", "Normaal", Room2),
                    new SeatModel("272", "1", "Normaal", Room2),
                    new SeatModel("273", "1", "Normaal", Room2),
                    new SeatModel("274", "1", "Normaal", Room2),
                    new SeatModel("275", "2", "Extra Beenruimte", Room2),
                    new SeatModel("276", "2", "Extra Beenruimte", Room2),
                    new SeatModel("277", "2", "Extra Beenruimte", Room2),
                    new SeatModel("278", "2", "Extra Beenruimte", Room2),
                    new SeatModel("279", "2", "Extra Beenruimte", Room2),
                    new SeatModel("280", "2", "Extra Beenruimte", Room2),
                    new SeatModel("281", "2", "Extra Beenruimte", Room2),
                    new SeatModel("282", "2", "Extra Beenruimte", Room2),
                    new SeatModel("283", "1", "Normaal", Room2),
                    new SeatModel("284", "1", "Normaal", Room2),
                    new SeatModel("285", "1", "Normaal", Room2),
                    new SeatModel("286", "1", "Normaal", Room2),
                    new SeatModel("287", " ", " ", Room2),
                    new SeatModel("288", " ", " ", Room2),
                    new SeatModel("289", "1", "Normaal", Room2),
                    new SeatModel("290", "1", "Normaal", Room2),
                    new SeatModel("291", "1", "Normaal", Room2),
                    new SeatModel("292", "1", "Normaal", Room2),
                    new SeatModel("293", "2", "Extra Beenruimte", Room2),
                    new SeatModel("294", "2", "Extra Beenruimte", Room2),
                    new SeatModel("295", "2", "Extra Beenruimte", Room2),
                    new SeatModel("296", "2", "Extra Beenruimte", Room2),
                    new SeatModel("297", "2", "Extra Beenruimte", Room2),
                    new SeatModel("298", "2", "Extra Beenruimte", Room2),
                    new SeatModel("299", "2", "Extra Beenruimte", Room2),
                    new SeatModel("300", "2", "Extra Beenruimte", Room2),
                    new SeatModel("301", "1", "Normaal", Room2),
                    new SeatModel("302", "1", "Normaal", Room2),
                    new SeatModel("303", "1", "Normaal", Room2),
                    new SeatModel("304", "1", "Normaal", Room2),
                    new SeatModel("305", " ", " ", Room2),
                    new SeatModel("306", " ", " ", Room2),
                    new SeatModel("307", "1", "Normaal", Room2),
                    new SeatModel("308", "1", "Normaal", Room2),
                    new SeatModel("309", "1", "Normaal", Room2),
                    new SeatModel("310", "1", "Normaal", Room2),
                    new SeatModel("311", "1", "Normaal", Room2),
                    new SeatModel("312", "2", "Extra Beenruimte", Room2),
                    new SeatModel("313", "2", "Extra Beenruimte", Room2),
                    new SeatModel("314", "2", "Extra Beenruimte", Room2),
                    new SeatModel("315", "2", "Extra Beenruimte", Room2),
                    new SeatModel("316", "2", "Extra Beenruimte", Room2),
                    new SeatModel("317", "2", "Extra Beenruimte", Room2),
                    new SeatModel("318", "1", "Normaal", Room2),
                    new SeatModel("319", "1", "Normaal", Room2),
                    new SeatModel("320", "1", "Normaal", Room2),
                    new SeatModel("321", "1", "Normaal", Room2),
                    new SeatModel("322", "1", "Normaal", Room2),
                    new SeatModel("323", " ", " ", Room2),
                    new SeatModel("324", " ", " ", Room2),
                    new SeatModel("325", "1", "Normaal", Room2),
                    new SeatModel("326", "1", "Normaal", Room2),
                    new SeatModel("327", "1", "Normaal", Room2),
                    new SeatModel("328", "1", "Normaal", Room2),
                    new SeatModel("329", "1", "Normaal", Room2),
                    new SeatModel("330", "1", "Normaal", Room2),
                    new SeatModel("331", "1", "Normaal", Room2),
                    new SeatModel("332", "1", "Normaal", Room2),
                    new SeatModel("333", "1", "Normaal", Room2),
                    new SeatModel("334", "1", "Normaal", Room2),
                    new SeatModel("335", "1", "Normaal", Room2),
                    new SeatModel("336", "1", "Normaal", Room2),
                    new SeatModel("337", "1", "Normaal", Room2),
                    new SeatModel("338", "1", "Normaal", Room2),
                    new SeatModel("339", "1", "Normaal", Room2),
                    new SeatModel("340", "1", "Normaal", Room2),
                    new SeatModel("341", " ", " ", Room2)
            };
            SeatModel[] layout3 = new SeatModel[] {
                    new SeatModel("0", " ", " ", Room3),
                    new SeatModel("1", " ", " ", Room3),
                    new SeatModel("2", " ", " ", Room3),
                    new SeatModel("3", " ", " ", Room3),
                    new SeatModel("4", " ", " ", Room3),
                    new SeatModel("5", " ", " ", Room3),
                    new SeatModel("6", " ", " ", Room3),
                    new SeatModel("7", " ", " ", Room3),
                    new SeatModel("8", "1", "Normaal", Room3),
                    new SeatModel("9", "1", "Normaal", Room3),
                    new SeatModel("10", "1", "Normaal", Room3),
                    new SeatModel("11", "1", "Normaal", Room3),
                    new SeatModel("12", "1", "Normaal", Room3),
                    new SeatModel("13", "1", "Normaal", Room3),
                    new SeatModel("14", "1", "Normaal", Room3),
                    new SeatModel("15", "1", "Normaal", Room3),
                    new SeatModel("16", "1", "Normaal", Room3),
                    new SeatModel("17", "1", "Normaal", Room3),
                    new SeatModel("18", "1", "Normaal", Room3),
                    new SeatModel("19", "1", "Normaal", Room3),
                    new SeatModel("20", "1", "Normaal", Room3),
                    new SeatModel("21", "1", "Normaal", Room3),
                    new SeatModel("22", " ", " ", Room3),
                    new SeatModel("23", " ", " ", Room3),
                    new SeatModel("24", " ", " ", Room3),
                    new SeatModel("25", " ", " ", Room3),
                    new SeatModel("26", " ", " ", Room3),
                    new SeatModel("27", " ", " ", Room3),
                    new SeatModel("28", " ", " ", Room3),
                    new SeatModel("29", " ", " ", Room3),
                    new SeatModel("30", " ", " ", Room3),
                    new SeatModel("31", " ", " ", Room3),
                    new SeatModel("32", " ", " ", Room3),
                    new SeatModel("33", " ", " ", Room3),
                    new SeatModel("34", " ", " ", Room3),
                    new SeatModel("35", " ", " ", Room3),
                    new SeatModel("36", " ", " ", Room3),
                    new SeatModel("37", "1", "Normaal", Room3),
                    new SeatModel("38", "1", "Normaal", Room3),
                    new SeatModel("39", "1", "Normaal", Room3),
                    new SeatModel("40", "1", "Normaal", Room3),
                    new SeatModel("41", "1", "Normaal", Room3),
                    new SeatModel("42", "1", "Normaal", Room3),
                    new SeatModel("43", "1", "Normaal", Room3),
                    new SeatModel("44", "1", "Normaal", Room3),
                    new SeatModel("45", "1", "Normaal", Room3),
                    new SeatModel("46", "1", "Normaal", Room3),
                    new SeatModel("47", "1", "Normaal", Room3),
                    new SeatModel("48", "1", "Normaal", Room3),
                    new SeatModel("49", "1", "Normaal", Room3),
                    new SeatModel("50", "1", "Normaal", Room3),
                    new SeatModel("51", "1", "Normaal", Room3),
                    new SeatModel("52", "1", "Normaal", Room3),
                    new SeatModel("53", " ", " ", Room3),
                    new SeatModel("54", " ", " ", Room3),
                    new SeatModel("55", " ", " ", Room3),
                    new SeatModel("56", " ", " ", Room3),
                    new SeatModel("57", " ", " ", Room3),
                    new SeatModel("58", " ", " ", Room3),
                    new SeatModel("59", " ", " ", Room3),
                    new SeatModel("60", " ", " ", Room3),
                    new SeatModel("61", " ", " ", Room3),
                    new SeatModel("62", " ", " ", Room3),
                    new SeatModel("63", " ", " ", Room3),
                    new SeatModel("64", " ", " ", Room3),
                    new SeatModel("65", "1", "Normaal", Room3),
                    new SeatModel("66", "1", "Normaal", Room3),
                    new SeatModel("67", "1", "Normaal", Room3),
                    new SeatModel("68", "1", "Normaal", Room3),
                    new SeatModel("69", "1", "Normaal", Room3),
                    new SeatModel("70", "1", "Normaal", Room3),
                    new SeatModel("71", "1", "Normaal", Room3),
                    new SeatModel("72", "1", "Normaal", Room3),
                    new SeatModel("73", "1", "Normaal", Room3),
                    new SeatModel("74", "1", "Normaal", Room3),
                    new SeatModel("75", "1", "Normaal", Room3),
                    new SeatModel("76", "1", "Normaal", Room3),
                    new SeatModel("77", "1", "Normaal", Room3),
                    new SeatModel("78", "1", "Normaal", Room3),
                    new SeatModel("79", "1", "Normaal", Room3),
                    new SeatModel("80", "1", "Normaal", Room3),
                    new SeatModel("81", "1", "Normaal", Room3),
                    new SeatModel("82", "1", "Normaal", Room3),
                    new SeatModel("83", "1", "Normaal", Room3),
                    new SeatModel("84", "1", "Normaal", Room3),
                    new SeatModel("85", " ", " ", Room3),
                    new SeatModel("86", " ", " ", Room3),
                    new SeatModel("87", " ", " ", Room3),
                    new SeatModel("88", " ", " ", Room3),
                    new SeatModel("89", " ", " ", Room3),
                    new SeatModel("90", " ", " ", Room3),
                    new SeatModel("91", " ", " ", Room3),
                    new SeatModel("92", " ", " ", Room3),
                    new SeatModel("93", "1", "Normaal", Room3),
                    new SeatModel("94", "1", "Normaal", Room3),
                    new SeatModel("95", "1", "Normaal", Room3),
                    new SeatModel("96", "1", "Normaal", Room3),
                    new SeatModel("97", "1", "Normaal", Room3),
                    new SeatModel("98", "1", "Normaal", Room3),
                    new SeatModel("99", "1", "Normaal", Room3),
                    new SeatModel("100", "1", "Normaal", Room3),
                    new SeatModel("101", "1", "Normaal", Room3),
                    new SeatModel("102", "2", "Extra Beenruimte", Room3),
                    new SeatModel("103", "2", "Extra Beenruimte", Room3),
                    new SeatModel("104", "2", "Extra Beenruimte", Room3),
                    new SeatModel("105", "2", "Extra Beenruimte", Room3),
                    new SeatModel("106", "2", "Extra Beenruimte", Room3),
                    new SeatModel("107", "2", "Extra Beenruimte", Room3),
                    new SeatModel("108", "1", "Normaal", Room3),
                    new SeatModel("109", "1", "Normaal", Room3),
                    new SeatModel("110", "1", "Normaal", Room3),
                    new SeatModel("111", "1", "Normaal", Room3),
                    new SeatModel("112", "1", "Normaal", Room3),
                    new SeatModel("113", "1", "Normaal", Room3),
                    new SeatModel("114", "1", "Normaal", Room3),
                    new SeatModel("115", "1", "Normaal", Room3),
                    new SeatModel("116", "1", "Normaal", Room3),
                    new SeatModel("117", " ", " ", Room3),
                    new SeatModel("118", " ", " ", Room3),
                    new SeatModel("119", " ", " ", Room3),
                    new SeatModel("120", " ", " ", Room3),
                    new SeatModel("121", " ", " ", Room3),
                    new SeatModel("122", " ", " ", Room3),
                    new SeatModel("123", "1", "Normaal", Room3),
                    new SeatModel("124", "1", "Normaal", Room3),
                    new SeatModel("125", "1", "Normaal", Room3),
                    new SeatModel("126", "1", "Normaal", Room3),
                    new SeatModel("127", "1", "Normaal", Room3),
                    new SeatModel("128", "1", "Normaal", Room3),
                    new SeatModel("129", "1", "Normaal", Room3),
                    new SeatModel("130", "2", "Extra Beenruimte", Room3),
                    new SeatModel("131", "2", "Extra Beenruimte", Room3),
                    new SeatModel("132", "2", "Extra Beenruimte", Room3),
                    new SeatModel("133", "2", "Extra Beenruimte", Room3),
                    new SeatModel("134", "2", "Extra Beenruimte", Room3),
                    new SeatModel("135", "2", "Extra Beenruimte", Room3),
                    new SeatModel("136", "2", "Extra Beenruimte", Room3),
                    new SeatModel("137", "2", "Extra Beenruimte", Room3),
                    new SeatModel("138", "2", "Extra Beenruimte", Room3),
                    new SeatModel("139", "2", "Extra Beenruimte", Room3),
                    new SeatModel("140", "1", "Normaal", Room3),
                    new SeatModel("141", "1", "Normaal", Room3),
                    new SeatModel("142", "1", "Normaal", Room3),
                    new SeatModel("143", "1", "Normaal", Room3),
                    new SeatModel("144", "1", "Normaal", Room3),
                    new SeatModel("145", "1", "Normaal", Room3),
                    new SeatModel("146", "1", "Normaal", Room3),
                    new SeatModel("147", " ", " ", Room3),
                    new SeatModel("148", " ", " ", Room3),
                    new SeatModel("149", " ", " ", Room3),
                    new SeatModel("150", " ", " ", Room3),
                    new SeatModel("151", " ", " ", Room3),
                    new SeatModel("152", "1", "Normaal", Room3),
                    new SeatModel("153", "1", "Normaal", Room3),
                    new SeatModel("154", "1", "Normaal", Room3),
                    new SeatModel("155", "1", "Normaal", Room3),
                    new SeatModel("156", "1", "Normaal", Room3),
                    new SeatModel("157", "1", "Normaal", Room3),
                    new SeatModel("158", "1", "Normaal", Room3),
                    new SeatModel("159", "2", "Extra Beenruimte", Room3),
                    new SeatModel("160", "2", "Extra Beenruimte", Room3),
                    new SeatModel("161", "2", "Extra Beenruimte", Room3),
                    new SeatModel("162", "2", "Extra Beenruimte", Room3),
                    new SeatModel("163", "2", "Extra Beenruimte", Room3),
                    new SeatModel("164", "2", "Extra Beenruimte", Room3),
                    new SeatModel("165", "2", "Extra Beenruimte", Room3),
                    new SeatModel("166", "2", "Extra Beenruimte", Room3),
                    new SeatModel("167", "2", "Extra Beenruimte", Room3),
                    new SeatModel("168", "2", "Extra Beenruimte", Room3),
                    new SeatModel("169", "2", "Extra Beenruimte", Room3),
                    new SeatModel("170", "2", "Extra Beenruimte", Room3),
                    new SeatModel("171", "1", "Normaal", Room3),
                    new SeatModel("172", "1", "Normaal", Room3),
                    new SeatModel("173", "1", "Normaal", Room3),
                    new SeatModel("174", "1", "Normaal", Room3),
                    new SeatModel("175", "1", "Normaal", Room3),
                    new SeatModel("176", "1", "Normaal", Room3),
                    new SeatModel("177", "1", "Normaal", Room3),
                    new SeatModel("178", " ", " ", Room3),
                    new SeatModel("179", " ", " ", Room3),
                    new SeatModel("180", " ", " ", Room3),
                    new SeatModel("181", " ", " ", Room3),
                    new SeatModel("182", "1", "Normaal", Room3),
                    new SeatModel("183", "1", "Normaal", Room3),
                    new SeatModel("184", "1", "Normaal", Room3),
                    new SeatModel("185", "1", "Normaal", Room3),
                    new SeatModel("186", "1", "Normaal", Room3),
                    new SeatModel("187", "1", "Normaal", Room3),
                    new SeatModel("188", "2", "Extra Beenruimte", Room3),
                    new SeatModel("189", "2", "Extra Beenruimte", Room3),
                    new SeatModel("190", "2", "Extra Beenruimte", Room3),
                    new SeatModel("191", "2", "Extra Beenruimte", Room3),
                    new SeatModel("192", "2", "Extra Beenruimte", Room3),
                    new SeatModel("193", "2", "Extra Beenruimte", Room3),
                    new SeatModel("194", "2", "Extra Beenruimte", Room3),
                    new SeatModel("195", "2", "Extra Beenruimte", Room3),
                    new SeatModel("196", "2", "Extra Beenruimte", Room3),
                    new SeatModel("197", "2", "Extra Beenruimte", Room3),
                    new SeatModel("198", "2", "Extra Beenruimte", Room3),
                    new SeatModel("199", "2", "Extra Beenruimte", Room3),
                    new SeatModel("200", "2", "Extra Beenruimte", Room3),
                    new SeatModel("201", "2", "Extra Beenruimte", Room3),
                    new SeatModel("202", "1", "Normaal", Room3),
                    new SeatModel("203", "1", "Normaal", Room3),
                    new SeatModel("204", "1", "Normaal", Room3),
                    new SeatModel("205", "1", "Normaal", Room3),
                    new SeatModel("206", "1", "Normaal", Room3),
                    new SeatModel("207", "1", "Normaal", Room3),
                    new SeatModel("208", " ", " ", Room3),
                    new SeatModel("209", " ", " ", Room3),
                    new SeatModel("210", " ", " ", Room3),
                    new SeatModel("211", "1", "Normaal", Room3),
                    new SeatModel("212", "1", "Normaal", Room3),
                    new SeatModel("213", "1", "Normaal", Room3),
                    new SeatModel("214", "1", "Normaal", Room3),
                    new SeatModel("215", "1", "Normaal", Room3),
                    new SeatModel("216", "1", "Normaal", Room3),
                    new SeatModel("217", "1", "Normaal", Room3),
                    new SeatModel("218", "2", "Extra Beenruimte", Room3),
                    new SeatModel("219", "2", "Extra Beenruimte", Room3),
                    new SeatModel("220", "2", "Extra Beenruimte", Room3),
                    new SeatModel("221", "2", "Extra Beenruimte", Room3),
                    new SeatModel("222", "2", "Extra Beenruimte", Room3),
                    new SeatModel("223", "3", "Love SeatModel", Room3),
                    new SeatModel("224", "3", "Love SeatModel", Room3),
                    new SeatModel("225", "3", "Love SeatModel", Room3),
                    new SeatModel("226", "3", "Love SeatModel", Room3),
                    new SeatModel("227", "2", "Extra Beenruimte", Room3),
                    new SeatModel("228", "2", "Extra Beenruimte", Room3),
                    new SeatModel("229", "2", "Extra Beenruimte", Room3),
                    new SeatModel("230", "2", "Extra Beenruimte", Room3),
                    new SeatModel("231", "2", "Extra Beenruimte", Room3),
                    new SeatModel("232", "1", "Normaal", Room3),
                    new SeatModel("233", "1", "Normaal", Room3),
                    new SeatModel("234", "1", "Normaal", Room3),
                    new SeatModel("235", "1", "Normaal", Room3),
                    new SeatModel("236", "1", "Normaal", Room3),
                    new SeatModel("237", "1", "Normaal", Room3),
                    new SeatModel("238", "1", "Normaal", Room3),
                    new SeatModel("239", " ", " ", Room3),
                    new SeatModel("240", "1", "Normaal", Room3),
                    new SeatModel("241", "1", "Normaal", Room3),
                    new SeatModel("242", "1", "Normaal", Room3),
                    new SeatModel("243", "1", "Normaal", Room3),
                    new SeatModel("244", "1", "Normaal", Room3),
                    new SeatModel("245", "1", "Normaal", Room3),
                    new SeatModel("246", "1", "Normaal", Room3),
                    new SeatModel("247", "2", "Extra Beenruimte", Room3),
                    new SeatModel("248", "2", "Extra Beenruimte", Room3),
                    new SeatModel("249", "2", "Extra Beenruimte", Room3),
                    new SeatModel("250", "2", "Extra Beenruimte", Room3),
                    new SeatModel("251", "3", "Love SeatModel", Room3),
                    new SeatModel("252", "3", "Love SeatModel", Room3),
                    new SeatModel("253", "3", "Love SeatModel", Room3),
                    new SeatModel("254", "3", "Love SeatModel", Room3),
                    new SeatModel("255", "3", "Love SeatModel", Room3),
                    new SeatModel("256", "3", "Love SeatModel", Room3),
                    new SeatModel("257", "3", "Love SeatModel", Room3),
                    new SeatModel("258", "3", "Love SeatModel", Room3),
                    new SeatModel("259", "2", "Extra Beenruimte", Room3),
                    new SeatModel("260", "2", "Extra Beenruimte", Room3),
                    new SeatModel("261", "2", "Extra Beenruimte", Room3),
                    new SeatModel("262", "2", "Extra Beenruimte", Room3),
                    new SeatModel("263", "1", "Normaal", Room3),
                    new SeatModel("264", "1", "Normaal", Room3),
                    new SeatModel("265", "1", "Normaal", Room3),
                    new SeatModel("266", "1", "Normaal", Room3),
                    new SeatModel("267", "1", "Normaal", Room3),
                    new SeatModel("268", "1", "Normaal", Room3),
                    new SeatModel("269", "1", "Normaal", Room3),
                    new SeatModel("270", "1", "Normaal", Room3),
                    new SeatModel("271", "1", "Normaal", Room3),
                    new SeatModel("272", "1", "Normaal", Room3),
                    new SeatModel("273", "1", "Normaal", Room3),
                    new SeatModel("274", "1", "Normaal", Room3),
                    new SeatModel("275", "1", "Normaal", Room3),
                    new SeatModel("276", "2", "Extra Beenruimte", Room3),
                    new SeatModel("277", "2", "Extra Beenruimte", Room3),
                    new SeatModel("278", "2", "Extra Beenruimte", Room3),
                    new SeatModel("279", "2", "Extra Beenruimte", Room3),
                    new SeatModel("280", "2", "Extra Beenruimte", Room3),
                    new SeatModel("281", "3", "Love SeatModel", Room3),
                    new SeatModel("282", "3", "Love SeatModel", Room3),
                    new SeatModel("283", "3", "Love SeatModel", Room3),
                    new SeatModel("284", "3", "Love SeatModel", Room3),
                    new SeatModel("285", "3", "Love SeatModel", Room3),
                    new SeatModel("286", "3", "Love SeatModel", Room3),
                    new SeatModel("287", "3", "Love SeatModel", Room3),
                    new SeatModel("288", "3", "Love SeatModel", Room3),
                    new SeatModel("289", "2", "Extra Beenruimte", Room3),
                    new SeatModel("290", "2", "Extra Beenruimte", Room3),
                    new SeatModel("291", "2", "Extra Beenruimte", Room3),
                    new SeatModel("292", "2", "Extra Beenruimte", Room3),
                    new SeatModel("293", "2", "Extra Beenruimte", Room3),
                    new SeatModel("294", "1", "Normaal", Room3),
                    new SeatModel("295", "1", "Normaal", Room3),
                    new SeatModel("296", "1", "Normaal", Room3),
                    new SeatModel("297", "1", "Normaal", Room3),
                    new SeatModel("298", "1", "Normaal", Room3),
                    new SeatModel("299", "1", "Normaal", Room3),
                    new SeatModel("300", "1", "Normaal", Room3),
                    new SeatModel("301", "1", "Normaal", Room3),
                    new SeatModel("302", "1", "Normaal", Room3),
                    new SeatModel("303", "1", "Normaal", Room3),
                    new SeatModel("304", "1", "Normaal", Room3),
                    new SeatModel("305", "2", "Extra Beenruimte", Room3),
                    new SeatModel("306", "2", "Extra Beenruimte", Room3),
                    new SeatModel("307", "2", "Extra Beenruimte", Room3),
                    new SeatModel("308", "2", "Extra Beenruimte", Room3),
                    new SeatModel("309", "2", "Extra Beenruimte", Room3),
                    new SeatModel("310", "2", "Extra Beenruimte", Room3),
                    new SeatModel("311", "3", "Love SeatModel", Room3),
                    new SeatModel("312", "3", "Love SeatModel", Room3),
                    new SeatModel("313", "3", "Love SeatModel", Room3),
                    new SeatModel("314", "3", "Love SeatModel", Room3),
                    new SeatModel("315", "3", "Love SeatModel", Room3),
                    new SeatModel("316", "3", "Love SeatModel", Room3),
                    new SeatModel("317", "3", "Love SeatModel", Room3),
                    new SeatModel("318", "3", "Love SeatModel", Room3),
                    new SeatModel("319", "2", "Extra Beenruimte", Room3),
                    new SeatModel("320", "2", "Extra Beenruimte", Room3),
                    new SeatModel("321", "2", "Extra Beenruimte", Room3),
                    new SeatModel("322", "2", "Extra Beenruimte", Room3),
                    new SeatModel("323", "2", "Extra Beenruimte", Room3),
                    new SeatModel("324", "2", "Extra Beenruimte", Room3),
                    new SeatModel("325", "1", "Normaal", Room3),
                    new SeatModel("326", "1", "Normaal", Room3),
                    new SeatModel("327", "1", "Normaal", Room3),
                    new SeatModel("328", "1", "Normaal", Room3),
                    new SeatModel("329", "1", "Normaal", Room3),
                    new SeatModel("330", "1", "Normaal", Room3),
                    new SeatModel("331", "1", "Normaal", Room3),
                    new SeatModel("332", "1", "Normaal", Room3),
                    new SeatModel("333", "1", "Normaal", Room3),
                    new SeatModel("334", "1", "Normaal", Room3),
                    new SeatModel("335", "2", "Extra Beenruimte", Room3),
                    new SeatModel("336", "2", "Extra Beenruimte", Room3),
                    new SeatModel("337", "2", "Extra Beenruimte", Room3),
                    new SeatModel("338", "2", "Extra Beenruimte", Room3),
                    new SeatModel("339", "2", "Extra Beenruimte", Room3),
                    new SeatModel("340", "2", "Extra Beenruimte", Room3),
                    new SeatModel("341", "3", "Love SeatModel", Room3),
                    new SeatModel("342", "3", "Love SeatModel", Room3),
                    new SeatModel("343", "3", "Love SeatModel", Room3),
                    new SeatModel("344", "3", "Love SeatModel", Room3),
                    new SeatModel("345", "3", "Love SeatModel", Room3),
                    new SeatModel("346", "3", "Love SeatModel", Room3),
                    new SeatModel("347", "3", "Love SeatModel", Room3),
                    new SeatModel("348", "3", "Love SeatModel", Room3),
                    new SeatModel("349", "2", "Extra Beenruimte", Room3),
                    new SeatModel("350", "2", "Extra Beenruimte", Room3),
                    new SeatModel("351", "2", "Extra Beenruimte", Room3),
                    new SeatModel("352", "2", "Extra Beenruimte", Room3),
                    new SeatModel("353", "2", "Extra Beenruimte", Room3),
                    new SeatModel("354", "2", "Extra Beenruimte", Room3),
                    new SeatModel("355", "1", "Normaal", Room3),
                    new SeatModel("356", "1", "Normaal", Room3),
                    new SeatModel("357", "1", "Normaal", Room3),
                    new SeatModel("358", "1", "Normaal", Room3),
                    new SeatModel("359", "1", "Normaal", Room3),
                    new SeatModel("360", "1", "Normaal", Room3),
                    new SeatModel("361", "1", "Normaal", Room3),
                    new SeatModel("362", "1", "Normaal", Room3),
                    new SeatModel("363", "1", "Normaal", Room3),
                    new SeatModel("364", "1", "Normaal", Room3),
                    new SeatModel("365", "1", "Normaal", Room3),
                    new SeatModel("366", "2", "Extra Beenruimte", Room3),
                    new SeatModel("367", "2", "Extra Beenruimte", Room3),
                    new SeatModel("368", "2", "Extra Beenruimte", Room3),
                    new SeatModel("369", "2", "Extra Beenruimte", Room3),
                    new SeatModel("370", "2", "Extra Beenruimte", Room3),
                    new SeatModel("371", "3", "Love SeatModel", Room3),
                    new SeatModel("372", "3", "Love SeatModel", Room3),
                    new SeatModel("373", "3", "Love SeatModel", Room3),
                    new SeatModel("374", "3", "Love SeatModel", Room3),
                    new SeatModel("375", "3", "Love SeatModel", Room3),
                    new SeatModel("376", "3", "Love SeatModel", Room3),
                    new SeatModel("377", "3", "Love SeatModel", Room3),
                    new SeatModel("378", "3", "Love SeatModel", Room3),
                    new SeatModel("379", "2", "Extra Beenruimte", Room3),
                    new SeatModel("380", "2", "Extra Beenruimte", Room3),
                    new SeatModel("381", "2", "Extra Beenruimte", Room3),
                    new SeatModel("382", "2", "Extra Beenruimte", Room3),
                    new SeatModel("383", "2", "Extra Beenruimte", Room3),
                    new SeatModel("384", "1", "Normaal", Room3),
                    new SeatModel("385", "1", "Normaal", Room3),
                    new SeatModel("386", "1", "Normaal", Room3),
                    new SeatModel("387", "1", "Normaal", Room3),
                    new SeatModel("388", "1", "Normaal", Room3),
                    new SeatModel("389", "1", "Normaal", Room3),
                    new SeatModel("390", " ", " ", Room3),
                    new SeatModel("391", "1", "Normaal", Room3),
                    new SeatModel("392", "1", "Normaal", Room3),
                    new SeatModel("393", "1", "Normaal", Room3),
                    new SeatModel("394", "1", "Normaal", Room3),
                    new SeatModel("395", "1", "Normaal", Room3),
                    new SeatModel("396", "2", "Extra Beenruimte", Room3),
                    new SeatModel("397", "2", "Extra Beenruimte", Room3),
                    new SeatModel("398", "2", "Extra Beenruimte", Room3),
                    new SeatModel("399", "2", "Extra Beenruimte", Room3),
                    new SeatModel("400", "2", "Extra Beenruimte", Room3),
                    new SeatModel("401", "3", "Love SeatModel", Room3),
                    new SeatModel("402", "3", "Love SeatModel", Room3),
                    new SeatModel("403", "3", "Love SeatModel", Room3),
                    new SeatModel("404", "3", "Love SeatModel", Room3),
                    new SeatModel("405", "3", "Love SeatModel", Room3),
                    new SeatModel("406", "3", "Love SeatModel", Room3),
                    new SeatModel("407", "3", "Love SeatModel", Room3),
                    new SeatModel("408", "3", "Love SeatModel", Room3),
                    new SeatModel("409", "2", "Extra Beenruimte", Room3),
                    new SeatModel("410", "2", "Extra Beenruimte", Room3),
                    new SeatModel("411", "2", "Extra Beenruimte", Room3),
                    new SeatModel("412", "2", "Extra Beenruimte", Room3),
                    new SeatModel("413", "2", "Extra Beenruimte", Room3),
                    new SeatModel("414", "1", "Normaal", Room3),
                    new SeatModel("415", "1", "Normaal", Room3),
                    new SeatModel("416", "1", "Normaal", Room3),
                    new SeatModel("417", "1", "Normaal", Room3),
                    new SeatModel("418", "1", "Normaal", Room3),
                    new SeatModel("419", " ", " ", Room3),
                    new SeatModel("420", " ", " ", Room3),
                    new SeatModel("421", " ", " ", Room3),
                    new SeatModel("422", "1", "Normaal", Room3),
                    new SeatModel("423", "1", "Normaal", Room3),
                    new SeatModel("424", "1", "Normaal", Room3),
                    new SeatModel("425", "1", "Normaal", Room3),
                    new SeatModel("426", "1", "Normaal", Room3),
                    new SeatModel("427", "2", "Extra Beenruimte", Room3),
                    new SeatModel("428", "2", "Extra Beenruimte", Room3),
                    new SeatModel("429", "2", "Extra Beenruimte", Room3),
                    new SeatModel("430", "2", "Extra Beenruimte", Room3),
                    new SeatModel("431", "2", "Extra Beenruimte", Room3),
                    new SeatModel("432", "3", "Love SeatModel", Room3),
                    new SeatModel("433", "3", "Love SeatModel", Room3),
                    new SeatModel("434", "3", "Love SeatModel", Room3),
                    new SeatModel("435", "3", "Love SeatModel", Room3),
                    new SeatModel("436", "3", "Love SeatModel", Room3),
                    new SeatModel("437", "3", "Love SeatModel", Room3),
                    new SeatModel("438", "2", "Extra Beenruimte", Room3),
                    new SeatModel("439", "2", "Extra Beenruimte", Room3),
                    new SeatModel("440", "2", "Extra Beenruimte", Room3),
                    new SeatModel("441", "2", "Extra Beenruimte", Room3),
                    new SeatModel("442", "2", "Extra Beenruimte", Room3),
                    new SeatModel("443", "1", "Normaal", Room3),
                    new SeatModel("444", "1", "Normaal", Room3),
                    new SeatModel("445", "1", "Normaal", Room3),
                    new SeatModel("446", "1", "Normaal", Room3),
                    new SeatModel("447", "1", "Normaal", Room3),
                    new SeatModel("448", " ", " ", Room3),
                    new SeatModel("449", " ", " ", Room3),
                    new SeatModel("450", " ", " ", Room3),
                    new SeatModel("451", " ", " ", Room3),
                    new SeatModel("452", " ", " ", Room3),
                    new SeatModel("453", "1", "Normaal", Room3),
                    new SeatModel("454", "1", "Normaal", Room3),
                    new SeatModel("455", "1", "Normaal", Room3),
                    new SeatModel("456", "1", "Normaal", Room3),
                    new SeatModel("457", "2", "Extra Beenruimte", Room3),
                    new SeatModel("458", "2", "Extra Beenruimte", Room3),
                    new SeatModel("459", "2", "Extra Beenruimte", Room3),
                    new SeatModel("460", "2", "Extra Beenruimte", Room3),
                    new SeatModel("461", "2", "Extra Beenruimte", Room3),
                    new SeatModel("462", "2", "Extra Beenruimte", Room3),
                    new SeatModel("463", "3", "Love SeatModel", Room3),
                    new SeatModel("464", "3", "Love SeatModel", Room3),
                    new SeatModel("465", "3", "Love SeatModel", Room3),
                    new SeatModel("466", "3", "Love SeatModel", Room3),
                    new SeatModel("467", "2", "Extra Beenruimte", Room3),
                    new SeatModel("468", "2", "Extra Beenruimte", Room3),
                    new SeatModel("469", "2", "Extra Beenruimte", Room3),
                    new SeatModel("470", "2", "Extra Beenruimte", Room3),
                    new SeatModel("471", "2", "Extra Beenruimte", Room3),
                    new SeatModel("472", "2", "Extra Beenruimte", Room3),
                    new SeatModel("473", "1", "Normaal", Room3),
                    new SeatModel("474", "1", "Normaal", Room3),
                    new SeatModel("475", "1", "Normaal", Room3),
                    new SeatModel("476", "1", "Normaal", Room3),
                    new SeatModel("477", " ", " ", Room3),
                    new SeatModel("478", " ", " ", Room3),
                    new SeatModel("479", " ", " ", Room3),
                    new SeatModel("480", " ", " ", Room3),
                    new SeatModel("481", " ", " ", Room3),
                    new SeatModel("482", " ", " ", Room3),
                    new SeatModel("483", "1", "Normaal", Room3),
                    new SeatModel("484", "1", "Normaal", Room3),
                    new SeatModel("485", "1", "Normaal", Room3),
                    new SeatModel("486", "1", "Normaal", Room3),
                    new SeatModel("487", "1", "Normaal", Room3),
                    new SeatModel("488", "2", "Extra Beenruimte", Room3),
                    new SeatModel("489", "2", "Extra Beenruimte", Room3),
                    new SeatModel("490", "2", "Extra Beenruimte", Room3),
                    new SeatModel("491", "2", "Extra Beenruimte", Room3),
                    new SeatModel("492", "2", "Extra Beenruimte", Room3),
                    new SeatModel("493", "2", "Extra Beenruimte", Room3),
                    new SeatModel("494", "2", "Extra Beenruimte", Room3),
                    new SeatModel("495", "2", "Extra Beenruimte", Room3),
                    new SeatModel("496", "2", "Extra Beenruimte", Room3),
                    new SeatModel("497", "2", "Extra Beenruimte", Room3),
                    new SeatModel("498", "2", "Extra Beenruimte", Room3),
                    new SeatModel("499", "2", "Extra Beenruimte", Room3),
                    new SeatModel("500", "2", "Extra Beenruimte", Room3),
                    new SeatModel("501", "2", "Extra Beenruimte", Room3),
                    new SeatModel("502", "1", "Normaal", Room3),
                    new SeatModel("503", "1", "Normaal", Room3),
                    new SeatModel("504", "1", "Normaal", Room3),
                    new SeatModel("505", "1", "Normaal", Room3),
                    new SeatModel("506", "1", "Normaal", Room3),
                    new SeatModel("507", " ", " ", Room3),
                    new SeatModel("508", " ", " ", Room3),
                    new SeatModel("509", " ", " ", Room3),
                    new SeatModel("510", " ", " ", Room3),
                    new SeatModel("511", " ", " ", Room3),
                    new SeatModel("512", " ", " ", Room3),
                    new SeatModel("513", "1", "Normaal", Room3),
                    new SeatModel("514", "1", "Normaal", Room3),
                    new SeatModel("515", "1", "Normaal", Room3),
                    new SeatModel("516", "1", "Normaal", Room3),
                    new SeatModel("517", "1", "Normaal", Room3),
                    new SeatModel("518", "2", "Extra Beenruimte", Room3),
                    new SeatModel("519", "2", "Extra Beenruimte", Room3),
                    new SeatModel("520", "2", "Extra Beenruimte", Room3),
                    new SeatModel("521", "2", "Extra Beenruimte", Room3),
                    new SeatModel("522", "2", "Extra Beenruimte", Room3),
                    new SeatModel("523", "2", "Extra Beenruimte", Room3),
                    new SeatModel("524", "2", "Extra Beenruimte", Room3),
                    new SeatModel("525", "2", "Extra Beenruimte", Room3),
                    new SeatModel("526", "2", "Extra Beenruimte", Room3),
                    new SeatModel("527", "2", "Extra Beenruimte", Room3),
                    new SeatModel("528", "2", "Extra Beenruimte", Room3),
                    new SeatModel("529", "2", "Extra Beenruimte", Room3),
                    new SeatModel("530", "2", "Extra Beenruimte", Room3),
                    new SeatModel("531", "2", "Extra Beenruimte", Room3),
                    new SeatModel("532", "1", "Normaal", Room3),
                    new SeatModel("533", "1", "Normaal", Room3),
                    new SeatModel("534", "1", "Normaal", Room3),
                    new SeatModel("535", "1", "Normaal", Room3),
                    new SeatModel("536", "1", "Normaal", Room3),
                    new SeatModel("537", " ", " ", Room3),
                    new SeatModel("538", " ", " ", Room3),
                    new SeatModel("539", " ", " ", Room3),
                    new SeatModel("540", " ", " ", Room3),
                    new SeatModel("541", " ", " ", Room3),
                    new SeatModel("542", " ", " ", Room3),
                    new SeatModel("543", "1", "Normaal", Room3),
                    new SeatModel("544", "1", "Normaal", Room3),
                    new SeatModel("545", "1", "Normaal", Room3),
                    new SeatModel("546", "1", "Normaal", Room3),
                    new SeatModel("547", "1", "Normaal", Room3),
                    new SeatModel("548", "1", "Normaal", Room3),
                    new SeatModel("549", "2", "Extra Beenruimte", Room3),
                    new SeatModel("550", "2", "Extra Beenruimte", Room3),
                    new SeatModel("551", "2", "Extra Beenruimte", Room3),
                    new SeatModel("552", "2", "Extra Beenruimte", Room3),
                    new SeatModel("553", "2", "Extra Beenruimte", Room3),
                    new SeatModel("554", "2", "Extra Beenruimte", Room3),
                    new SeatModel("555", "2", "Extra Beenruimte", Room3),
                    new SeatModel("556", "2", "Extra Beenruimte", Room3),
                    new SeatModel("557", "2", "Extra Beenruimte", Room3),
                    new SeatModel("558", "2", "Extra Beenruimte", Room3),
                    new SeatModel("559", "2", "Extra Beenruimte", Room3),
                    new SeatModel("560", "2", "Extra Beenruimte", Room3),
                    new SeatModel("561", "1", "Normaal", Room3),
                    new SeatModel("562", "1", "Normaal", Room3),
                    new SeatModel("563", "1", "Normaal", Room3),
                    new SeatModel("564", "1", "Normaal", Room3),
                    new SeatModel("565", "1", "Normaal", Room3),
                    new SeatModel("566", "1", "Normaal", Room3),
                    new SeatModel("567", " ", " ", Room3),
                    new SeatModel("568", " ", " ", Room3),
                    new SeatModel("569", " ", " ", Room3),
                    new SeatModel("570", " ", " ", Room3),
                    new SeatModel("571", " ", " ", Room3),
                    new SeatModel("572", " ", " ", Room3),
                    new SeatModel("573", " ", " ", Room3),
                    new SeatModel("574", "1", "Normaal", Room3),
                    new SeatModel("575", "1", "Normaal", Room3),
                    new SeatModel("576", "1", "Normaal", Room3),
                    new SeatModel("577", "1", "Normaal", Room3),
                    new SeatModel("578", "1", "Normaal", Room3),
                    new SeatModel("579", "1", "Normaal", Room3),
                    new SeatModel("580", "1", "Normaal", Room3),
                    new SeatModel("581", "1", "Normaal", Room3),
                    new SeatModel("582", "1", "Normaal", Room3),
                    new SeatModel("583", "1", "Normaal", Room3),
                    new SeatModel("584", "1", "Normaal", Room3),
                    new SeatModel("585", "1", "Normaal", Room3),
                    new SeatModel("586", "1", "Normaal", Room3),
                    new SeatModel("587", "1", "Normaal", Room3),
                    new SeatModel("588", "1", "Normaal", Room3),
                    new SeatModel("589", "1", "Normaal", Room3),
                    new SeatModel("590", "1", "Normaal", Room3),
                    new SeatModel("591", "1", "Normaal", Room3),
                    new SeatModel("592", "1", "Normaal", Room3),
                    new SeatModel("593", "1", "Normaal", Room3),
                    new SeatModel("594", "1", "Normaal", Room3),
                    new SeatModel("595", "1", "Normaal", Room3),
                    new SeatModel("596", " ", " ", Room3),
                    new SeatModel("597", " ", " ", Room3),
                    new SeatModel("598", " ", " ", Room3),
                    new SeatModel("599", " ", " ", Room3)
            };

            try
            {

                //----- Assigning seats to the rooms -----//
                Room1.AddSeatModels(layout1);
                Room2.AddSeatModels(layout2);
                Room3.AddSeatModels(layout3);

                //----- Saving to Database -----//
                rf.CreateItem(Room1);
                rf.CreateItem(Room2);
                rf.CreateItem(Room3);

                //Console.WriteLine("\n--- 100% ---\nLayout database setup!");
            }
            catch (Exception ex)
            {
                Console.WriteLine("X Layout database setup : Something went wrong!\n" + ex);
                
                
                
                
                
                ;
            }
        }

    }
}
