using DataAccessLibrary;
using System;
using System.Data.SQLite;
using System.IO;
using System.Text.Json;
using System.Xml.Linq;

namespace Project_B
{
    class SQLite
    {
        /// <summary>
        /// TEMPORARY FUNCTION : Made to upload a new Layout to the database.
        /// </summary>
        /// <param name="layout"></param>
        /// <param name="room"></param>
        public static void upload_to_database(List<Seat> seats, Room room)
        {
            SQLiteConnection sqlite_conn;
            sqlite_conn = CreateConnection();

            try
            {
                ExcecuteQuerry(sqlite_conn, $@"INSERT INTO Room(
                    Name,
                    Capacity,
                    RowWidth
                ) VALUES (
                    '{room.Name}',
                    {room.Capacity},
                    {room.RowWidth}
                ); ");
                foreach (Seat seat in seats)
                {
                    ExcecuteQuerry(sqlite_conn, $@"INSERT INTO Seat(
                    RoomID,
                    Name,
                    Rank,
                    Type
                ) VALUES (
                    {seat.RoomID},
                    '{seat.Name}',
                    '{seat.Rank}',
                    '{seat.Type}'
                ); ");
                }
            }
            catch { sqlite_conn.Close(); }
            sqlite_conn.Close();
        }
        /// <summary>
        /// Standard setup data and database tables needed for projectB.
        /// </summary>
        public static void SetupProjectB()
        {
            SQLiteConnection sqlite_conn = CreateConnection();

            try
            {
                //sqlite_conn = CreateConnection();

                //----- Creating Tables -----//
                ExcecuteQuerry(sqlite_conn, @"CREATE TABLE Author(
                    ID INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL ,
                    Name TEXT  NOT NULL,
                    Description TEXT  NOT NULL,
                    Age INTEGER  NOT NULL
                )");
                ExcecuteQuerry(sqlite_conn, @"CREATE TABLE Director(
                    ID INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL ,
                    Name TEXT  NOT NULL,
                    Discription TEXT  NOT NULL,
                    Age INTEGER  NOT NULL
                )");
                ExcecuteQuerry(sqlite_conn, @"CREATE TABLE Movie(
                    ID INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL ,
                    Title TEXT  NOT NULL,
                    DirectorID INTEGER  NOT NULL,
                    pegiAge INTEGER  NOT NULL,
                    Discription TEXT  NOT NULL,
                    Genre TEXT  NOT NULL,
                    DurationInMin INTEGER  NOT NULL,
                    FOREIGN KEY (DirectorID) REFERENCES Director (ID)
                )");
                ExcecuteQuerry(sqlite_conn, @"CREATE TABLE Room(
                    ID INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL ,
                    Name TEXT  NOT NULL,
                    Capacity INTEGER  NOT NULL,
                    RowWidth INTEGER  NOT NULL
                )");
                ExcecuteQuerry(sqlite_conn, @"CREATE TABLE TimeTable(
                    ID INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL ,
                    MovieID INTEGER  NOT NULL,
                    RoomID INTEGER  NOT NULL,
                    StartDate TEXT  NOT NULL,
                    EndDate TEXT  NOT NULL,
                    FOREIGN KEY (MovieID) REFERENCES Movie (ID),
                    FOREIGN KEY (RoomID) REFERENCES Room (ID)
                )");
                ExcecuteQuerry(sqlite_conn, @"CREATE TABLE AuthorInMovie(
                    ID INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL ,
                    AuthorID INTEGER  NOT NULL,
                    MovieID INTEGER  NOT NULL,
                    FOREIGN KEY (AuthorID) REFERENCES Author (ID),
                    FOREIGN KEY (MovieID) REFERENCES Movie (ID)
                )");
                ExcecuteQuerry(sqlite_conn, @"CREATE TABLE Costumer(
                    ID INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL ,
                    Name TEXT  NOT NULL,
                    Age INTEGER  NOT NULL,
                    Email TEXT  NOT NULL,
                    PhoneNumber TEXT  NOT NULL,
                    IsSubsxribed INTEGER  NOT NULL
                )");
                ExcecuteQuerry(sqlite_conn, @"CREATE TABLE Reservation(
                    ID INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL ,
                    CostumerID INTEGER  NOT NULL,
                    TimeTableID INTEGER  NOT NULL,
                    Note TEXT  NOT NULL,
                    FOREIGN KEY (CostumerID) REFERENCES Costumer (ID),
                    FOREIGN KEY (TimeTableID) REFERENCES TimeTable (ID)
                )");
                ExcecuteQuerry(sqlite_conn, @"CREATE TABLE Seat(
                    ID INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL ,
                    RoomID INTEGER  NOT NULL,
                    Name TEXT  NOT NULL,
                    Rank TEXT  NOT NULL,
                    Type TEXT  NOT NULL,
                    FOREIGN KEY (RoomID) REFERENCES Room (ID)
                )");
                ExcecuteQuerry(sqlite_conn, @"CREATE TABLE ReservedSeat(
                    ID INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL ,
                    SeatID INTEGER  NOT NULL,
                    ReservationID INTEGER  NOT NULL,
                    FOREIGN KEY (SeatID) REFERENCES Seat (ID),
                    FOREIGN KEY (ReservationID) REFERENCES Reservation (ID)
                )");

                //----- Inputting test data -----//
                ExcecuteQuerry(sqlite_conn, @"INSERT INTO Author(
                    Name,
                    Description,
                    Age
                ) VALUES (
                    'Test',
                    'Test',
                    1
                ); ");
                ExcecuteQuerry(sqlite_conn, @"INSERT INTO AuthorInMovie(
                    AuthorID,
                    MovieID
                ) VALUES (
                    1,
                    1
                ); ");
                ExcecuteQuerry(sqlite_conn, @"INSERT INTO Costumer(
                    Name,
                    Age,
                    Email,
                    PhoneNumber,
                    IsSubsxribed
                ) VALUES (
                    'Test',
                    1,
                    'Test',
                    'Test',
                    1
                ); ");
                ExcecuteQuerry(sqlite_conn, @"INSERT INTO Director(
                    Name,
                    Discription,
                    Age
                ) VALUES (
                    'Test',
                    'Test',
                    1
                ); ");
                ExcecuteQuerry(sqlite_conn, @"INSERT INTO Movie(
                    Title,
                    DirectorID,
                    pegiAge,
                    Discription,
                    Genre,
                    DurationInMin
                ) VALUES (
                    'Title',
                    1,
                    1,
                    'Test',
                    'Test',
                    1
                ); ");
                ExcecuteQuerry(sqlite_conn, @"INSERT INTO Reservation(
                    CostumerID,
                    TimeTableID,
                    Note
                ) VALUES (
                    1,
                    1,
                    'Test'
                ); ");
                ExcecuteQuerry(sqlite_conn, @"INSERT INTO ReservedSeat(
                    SeatID,
                    ReservationID
                ) VALUES (
                    1,
                    1
                ); ");
                /*ExcecuteQuerry(sqlite_conn, @"INSERT INTO Room(
                    Name,
                    Capacity,
                    RowWidth
                ) VALUES (
                    'Test',
                    1,
                    1
                ); ");
                ExcecuteQuerry(sqlite_conn, @"INSERT INTO Seat(
                    RoomID,
                    Name,
                    Rank,
                    Type
                ) VALUES (
                    1,
                    'Test',
                    'Test',
                    'Test'
                ); ");*/
                
                DateTime StartDateData = new DateTime(2024, 3, 24, 12, 0, 0);
                /*Console.WriteLine($@"
                    {StartDateData.ToString("yyyy-MM-dd HH:mm:ss")}\n
                    {StartDateData.AddMinutes(120).ToString("yyyy-MM-dd HH:mm:ss")}\n
                ");*/
                ExcecuteQuerry(sqlite_conn, $@"INSERT INTO TimeTable(
                    MovieID,
                    RoomID,
                    StartDate,
                    EndDate
                ) VALUES (
                    1,
                    1,
                    '{StartDateData.ToString("yyyy-MM-dd HH:mm:ss")}',
                    '{StartDateData.AddMinutes(120).ToString("yyyy-MM-dd HH:mm:ss")}'
                ); ");


                //Print data
                //ReadData(sqlite_conn);
                sqlite_conn.Close();
                Console.WriteLine("\n--- 50% ---\nDatabase setup!");
            }
            catch (Exception) { Console.WriteLine("X Database setup : Something went wrong!"); }
            finally { sqlite_conn.Close(); }
            if (true /* getRoomsFromDatabase().Count() >= 3 - Aymane */)
            {
                List<Seat> layout1 = new List<Seat> {
                    new Seat(0, 1, "0", " ", " "),
                    new Seat(1, 1, "1", " ", " "),
                    new Seat(2, 1, "2", "1", "Normaal"),
                    new Seat(3, 1, "3", "1", "Normaal"),
                    new Seat(4, 1, "4", "1", "Normaal"),
                    new Seat(5, 1, "5", "1", "Normaal"),
                    new Seat(6, 1, "6", "1", "Normaal"),
                    new Seat(7, 1, "7", "1", "Normaal"),
                    new Seat(8, 1, "8", "1", "Normaal"),
                    new Seat(9, 1, "9", "1", "Normaal"),
                    new Seat(10, 1, "10", " ", " "),
                    new Seat(11, 1, "11", " ", " "),
                    new Seat(12, 1, "12", " ", " "),
                    new Seat(13, 1, "13", " ", " "),
                    new Seat(14, 1, "14", "1", "Normaal"),
                    new Seat(15, 1, "15", "1", "Normaal"),
                    new Seat(16, 1, "16", "1", "Normaal"),
                    new Seat(17, 1, "17", "1", "Normaal"),
                    new Seat(18, 1, "18", "1", "Normaal"),
                    new Seat(19, 1, "19", "1", "Normaal"),
                    new Seat(20, 1, "20", "1", "Normaal"),
                    new Seat(21, 1, "21", "1", "Normaal"),
                    new Seat(22, 1, "22", " ", " "),
                    new Seat(23, 1, "23", " ", " "),
                    new Seat(24, 1, "24", " ", " "),
                    new Seat(25, 1, "25", "1", "Normaal"),
                    new Seat(26, 1, "26", "1", "Normaal"),
                    new Seat(27, 1, "27", "1", "Normaal"),
                    new Seat(28, 1, "28", "1", "Normaal"),
                    new Seat(29, 1, "29", "1", "Normaal"),
                    new Seat(30, 1, "30", "1", "Normaal"),
                    new Seat(31, 1, "31", "1", "Normaal"),
                    new Seat(32, 1, "32", "1", "Normaal"),
                    new Seat(33, 1, "33", "1", "Normaal"),
                    new Seat(34, 1, "34", "1", "Normaal"),
                    new Seat(35, 1, "35", " ", " "),
                    new Seat(36, 1, "36", "1", "Normaal"),
                    new Seat(37, 1, "37", "1", "Normaal"),
                    new Seat(38, 1, "38", "1", "Normaal"),
                    new Seat(39, 1, "39", "1", "Normaal"),
                    new Seat(40, 1, "40", "1", "Normaal"),
                    new Seat(41, 1, "41", "2", "Normaal"),
                    new Seat(42, 1, "42", "2", "Normaal"),
                    new Seat(43, 1, "43", "1", "Normaal"),
                    new Seat(44, 1, "44", "1", "Normaal"),
                    new Seat(45, 1, "45", "1", "Normaal"),
                    new Seat(46, 1, "46", "1", "Normaal"),
                    new Seat(47, 1, "47", "1", "Normaal"),
                    new Seat(48, 1, "48", "1", "Normaal"),
                    new Seat(49, 1, "49", "1", "Normaal"),
                    new Seat(50, 1, "50", "1", "Normaal"),
                    new Seat(51, 1, "51", "1", "Normaal"),
                    new Seat(52, 1, "52", "2", "Normaal"),
                    new Seat(53, 1, "53", "2", "Normaal"),
                    new Seat(54, 1, "54", "2", "Normaal"),
                    new Seat(55, 1, "55", "2", "Normaal"),
                    new Seat(56, 1, "56", "1", "Normaal"),
                    new Seat(57, 1, "57", "1", "Normaal"),
                    new Seat(58, 1, "58", "1", "Normaal"),
                    new Seat(59, 1, "59", "1", "Normaal"),
                    new Seat(60, 1, "60", "1", "Normaal"),
                    new Seat(61, 1, "61", "1", "Normaal"),
                    new Seat(62, 1, "62", "1", "Normaal"),
                    new Seat(63, 1, "63", "2", "Normaal"),
                    new Seat(64, 1, "64", "2", "Normaal"),
                    new Seat(65, 1, "65", "3", "Normaal"),
                    new Seat(66, 1, "66", "3", "Normaal"),
                    new Seat(67, 1, "67", "2", "Normaal"),
                    new Seat(68, 1, "68", "2", "Normaal"),
                    new Seat(69, 1, "69", "1", "Normaal"),
                    new Seat(70, 1, "70", "1", "Normaal"),
                    new Seat(71, 1, "71", "1", "Normaal"),
                    new Seat(72, 1, "72", "1", "Normaal"),
                    new Seat(73, 1, "73", "1", "Normaal"),
                    new Seat(74, 1, "74", "1", "Normaal"),
                    new Seat(75, 1, "75", "2", "Normaal"),
                    new Seat(76, 1, "76", "2", "Normaal"),
                    new Seat(77, 1, "77", "3", "Normaal"),
                    new Seat(78, 1, "78", "3", "Normaal"),
                    new Seat(79, 1, "79", "2", "Normaal"),
                    new Seat(80, 1, "80", "2", "Normaal"),
                    new Seat(81, 1, "81", "1", "Normaal"),
                    new Seat(82, 1, "82", "1", "Normaal"),
                    new Seat(83, 1, "83", "1", "Normaal"),
                    new Seat(84, 1, "84", "1", "Normaal"),
                    new Seat(85, 1, "85", "1", "Normaal"),
                    new Seat(86, 1, "86", "1", "Normaal"),
                    new Seat(87, 1, "87", "2", "Normaal"),
                    new Seat(88, 1, "88", "2", "Normaal"),
                    new Seat(89, 1, "89", "3", "Normaal"),
                    new Seat(90, 1, "90", "3", "Normaal"),
                    new Seat(91, 1, "91", "2", "Normaal"),
                    new Seat(92, 1, "92", "2", "Normaal"),
                    new Seat(93, 1, "93", "1", "Normaal"),
                    new Seat(94, 1, "94", "1", "Normaal"),
                    new Seat(95, 1, "95", "1", "Normaal"),
                    new Seat(96, 1, "96", "1", "Normaal"),
                    new Seat(97, 1, "97", "1", "Normaal"),
                    new Seat(98, 1, "98", "1", "Normaal"),
                    new Seat(99, 1, "99", "2", "Normaal"),
                    new Seat(100, 1, "100", "2", "Normaal"),
                    new Seat(101, 1, "101", "3", "Normaal"),
                    new Seat(102, 1, "102", "3", "Normaal"),
                    new Seat(103, 1, "103", "2", "Normaal"),
                    new Seat(104, 1, "104", "2", "Normaal"),
                    new Seat(105, 1, "105", "1", "Normaal"),
                    new Seat(106, 1, "106", "1", "Normaal"),
                    new Seat(107, 1, "107", "1", "Normaal"),
                    new Seat(108, 1, "108", "1", "Normaal"),
                    new Seat(109, 1, "109", "1", "Normaal"),
                    new Seat(110, 1, "110", "1", "Normaal"),
                    new Seat(111, 1, "111", "1", "Normaal"),
                    new Seat(112, 1, "112", "2", "Normaal"),
                    new Seat(113, 1, "113", "2", "Normaal"),
                    new Seat(114, 1, "114", "2", "Normaal"),
                    new Seat(115, 1, "115", "2", "Normaal"),
                    new Seat(116, 1, "116", "1", "Normaal"),
                    new Seat(117, 1, "117", "1", "Normaal"),
                    new Seat(118, 1, "118", "1", "Normaal"),
                    new Seat(119, 1, "119", "1", "Normaal"),
                    new Seat(120, 1, "120", "1", "Normaal"),
                    new Seat(121, 1, "121", "1", "Normaal"),
                    new Seat(122, 1, "122", "1", "Normaal"),
                    new Seat(123, 1, "123", "1", "Normaal"),
                    new Seat(124, 1, "124", "1", "Normaal"),
                    new Seat(125, 1, "125", "2", "Normaal"),
                    new Seat(126, 1, "126", "2", "Normaal"),
                    new Seat(127, 1, "127", "1", "Normaal"),
                    new Seat(128, 1, "128", "1", "Normaal"),
                    new Seat(129, 1, "129", "1", "Normaal"),
                    new Seat(130, 1, "130", "1", "Normaal"),
                    new Seat(131, 1, "131", "1", "Normaal"),
                    new Seat(132, 1, "132", " ", " "),
                    new Seat(133, 1, "133", "1", "Normaal"),
                    new Seat(134, 1, "134", "1", "Normaal"),
                    new Seat(135, 1, "135", "1", "Normaal"),
                    new Seat(136, 1, "136", "1", "Normaal"),
                    new Seat(137, 1, "137", "1", "Normaal"),
                    new Seat(138, 1, "138", "1", "Normaal"),
                    new Seat(139, 1, "139", "1", "Normaal"),
                    new Seat(140, 1, "140", "1", "Normaal"),
                    new Seat(141, 1, "141", "1", "Normaal"),
                    new Seat(142, 1, "142", "1", "Normaal"),
                    new Seat(143, 1, "143", " ", " "),
                    new Seat(144, 1, "144", " ", " "),
                    new Seat(145, 1, "145", "1", "Normaal"),
                    new Seat(146, 1, "146", "1", "Normaal"),
                    new Seat(147, 1, "147", "1", "Normaal"),
                    new Seat(148, 1, "148", "1", "Normaal"),
                    new Seat(149, 1, "149", "1", "Normaal"),
                    new Seat(150, 1, "150", "1", "Normaal"),
                    new Seat(151, 1, "151", "1", "Normaal"),
                    new Seat(152, 1, "152", "1", "Normaal"),
                    new Seat(153, 1, "153", "1", "Normaal"),
                    new Seat(154, 1, "154", "1", "Normaal"),
                    new Seat(155, 1, "155", " ", " "),
                    new Seat(156, 1, "156", " ", " "),
                    new Seat(157, 1, "157", " ", " "),
                    new Seat(158, 1, "158", "1", "Normaal"),
                    new Seat(159, 1, "159", "1", "Normaal"),
                    new Seat(160, 1, "160", "1", "Normaal"),
                    new Seat(161, 1, "161", "1", "Normaal"),
                    new Seat(162, 1, "162", "1", "Normaal"),
                    new Seat(163, 1, "163", "1", "Normaal"),
                    new Seat(164, 1, "164", "1", "Normaal"),
                    new Seat(165, 1, "165", "1", "Normaal"),
                    new Seat(166, 1, "166", " ", " "),
                    new Seat(167, 1, "167", " ", " ")
                };
                List<Seat> layout2 = new List<Seat> {
                    new Seat(0, 2, "0", " ", " "),
                    new Seat(1, 2, "1", " ", " "),
                    new Seat(2, 2, "2", " ", " "),
                    new Seat(3, 2, "3", "1", "Normaal"),
                    new Seat(4, 2, "4", "1", "Normaal"),
                    new Seat(5, 2, "5", "1", "Normaal"),
                    new Seat(6, 2, "6", "1", "Normaal"),
                    new Seat(7, 2, "7", "1", "Normaal"),
                    new Seat(8, 2, "8", "1", "Normaal"),
                    new Seat(9, 2, "9", "1", "Normaal"),
                    new Seat(10, 2, "10", "1", "Normaal"),
                    new Seat(11, 2, "11", "1", "Normaal"),
                    new Seat(12, 2, "12", "1", "Normaal"),
                    new Seat(13, 2, "13", "1", "Normaal"),
                    new Seat(14, 2, "14", "1", "Normaal"),
                    new Seat(15, 2, "15", " ", " "),
                    new Seat(16, 2, "16", " ", " "),
                    new Seat(17, 2, "17", " ", " "),
                    new Seat(18, 2, "18", " ", " "),
                    new Seat(19, 2, "19", " ", " "),
                    new Seat(20, 2, "20", " ", " "),
                    new Seat(21, 2, "21", "1", "Normaal"),
                    new Seat(22, 2, "22", "1", "Normaal"),
                    new Seat(23, 2, "23", "1", "Normaal"),
                    new Seat(24, 2, "24", "1", "Normaal"),
                    new Seat(25, 2, "25", "1", "Normaal"),
                    new Seat(26, 2, "26", "1", "Normaal"),
                    new Seat(27, 2, "27", "1", "Normaal"),
                    new Seat(28, 2, "28", "1", "Normaal"),
                    new Seat(29, 2, "29", "1", "Normaal"),
                    new Seat(30, 2, "30", "1", "Normaal"),
                    new Seat(31, 2, "31", "1", "Normaal"),
                    new Seat(32, 2, "32", "1", "Normaal"),
                    new Seat(33, 2, "33", " ", " "),
                    new Seat(34, 2, "34", " ", " "),
                    new Seat(35, 2, "35", " ", " "),
                    new Seat(36, 2, "36", " ", " "),
                    new Seat(37, 2, "37", " ", " "),
                    new Seat(38, 2, "38", "1", "Normaal"),
                    new Seat(39, 2, "39", "1", "Normaal"),
                    new Seat(40, 2, "40", "1", "Normaal"),
                    new Seat(41, 2, "41", "1", "Normaal"),
                    new Seat(42, 2, "42", "1", "Normaal"),
                    new Seat(43, 2, "43", "1", "Normaal"),
                    new Seat(44, 2, "44", "1", "Normaal"),
                    new Seat(45, 2, "45", "1", "Normaal"),
                    new Seat(46, 2, "46", "1", "Normaal"),
                    new Seat(47, 2, "47", "1", "Normaal"),
                    new Seat(48, 2, "48", "1", "Normaal"),
                    new Seat(49, 2, "49", "1", "Normaal"),
                    new Seat(50, 2, "50", "1", "Normaal"),
                    new Seat(51, 2, "51", "1", "Normaal"),
                    new Seat(52, 2, "52", " ", " "),
                    new Seat(53, 2, "53", " ", " "),
                    new Seat(54, 2, "54", " ", " "),
                    new Seat(55, 2, "55", " ", " "),
                    new Seat(56, 2, "56", "1", "Normaal"),
                    new Seat(57, 2, "57", "1", "Normaal"),
                    new Seat(58, 2, "58", "1", "Normaal"),
                    new Seat(59, 2, "59", "1", "Normaal"),
                    new Seat(60, 2, "60", "2", "Normaal"),
                    new Seat(61, 2, "61", "2", "Normaal"),
                    new Seat(62, 2, "62", "2", "Normaal"),
                    new Seat(63, 2, "63", "2", "Normaal"),
                    new Seat(64, 2, "64", "2", "Normaal"),
                    new Seat(65, 2, "65", "2", "Normaal"),
                    new Seat(66, 2, "66", "1", "Normaal"),
                    new Seat(67, 2, "67", "1", "Normaal"),
                    new Seat(68, 2, "68", "1", "Normaal"),
                    new Seat(69, 2, "69", "1", "Normaal"),
                    new Seat(70, 2, "70", " ", " "),
                    new Seat(71, 2, "71", " ", " "),
                    new Seat(72, 2, "72", " ", " "),
                    new Seat(73, 2, "73", " ", " "),
                    new Seat(74, 2, "74", "1", "Normaal"),
                    new Seat(75, 2, "75", "1", "Normaal"),
                    new Seat(76, 2, "76", "1", "Normaal"),
                    new Seat(77, 2, "77", "1", "Normaal"),
                    new Seat(78, 2, "78", "2", "Normaal"),
                    new Seat(79, 2, "79", "2", "Normaal"),
                    new Seat(80, 2, "80", "2", "Normaal"),
                    new Seat(81, 2, "81", "2", "Normaal"),
                    new Seat(82, 2, "82", "2", "Normaal"),
                    new Seat(83, 2, "83", "2", "Normaal"),
                    new Seat(84, 2, "84", "1", "Normaal"),
                    new Seat(85, 2, "85", "1", "Normaal"),
                    new Seat(86, 2, "86", "1", "Normaal"),
                    new Seat(87, 2, "87", "1", "Normaal"),
                    new Seat(88, 2, "88", " ", " "),
                    new Seat(89, 2, "89", " ", " "),
                    new Seat(90, 2, "90", " ", " "),
                    new Seat(91, 2, "91", "1", "Normaal"),
                    new Seat(92, 2, "92", "1", "Normaal"),
                    new Seat(93, 2, "93", "1", "Normaal"),
                    new Seat(94, 2, "94", "1", "Normaal"),
                    new Seat(95, 2, "95", "2", "Normaal"),
                    new Seat(96, 2, "96", "2", "Normaal"),
                    new Seat(97, 2, "97", "2", "Normaal"),
                    new Seat(98, 2, "98", "2", "Normaal"),
                    new Seat(99, 2, "99", "2", "Normaal"),
                    new Seat(100, 2, "100", "2", "Normaal"),
                    new Seat(101, 2, "101", "2", "Normaal"),
                    new Seat(102, 2, "102", "2", "Normaal"),
                    new Seat(103, 2, "103", "1", "Normaal"),
                    new Seat(104, 2, "104", "1", "Normaal"),
                    new Seat(105, 2, "105", "1", "Normaal"),
                    new Seat(106, 2, "106", "1", "Normaal"),
                    new Seat(107, 2, "107", " ", " "),
                    new Seat(108, 2, "108", " ", " "),
                    new Seat(109, 2, "109", "1", "Normaal"),
                    new Seat(110, 2, "110", "1", "Normaal"),
                    new Seat(111, 2, "111", "1", "Normaal"),
                    new Seat(112, 2, "112", "2", "Normaal"),
                    new Seat(113, 2, "113", "2", "Normaal"),
                    new Seat(114, 2, "114", "2", "Normaal"),
                    new Seat(115, 2, "115", "2", "Normaal"),
                    new Seat(116, 2, "116", "3", "Normaal"),
                    new Seat(117, 2, "117", "3", "Normaal"),
                    new Seat(118, 2, "118", "2", "Normaal"),
                    new Seat(119, 2, "119", "2", "Normaal"),
                    new Seat(120, 2, "120", "2", "Normaal"),
                    new Seat(121, 2, "121", "2", "Normaal"),
                    new Seat(122, 2, "122", "1", "Normaal"),
                    new Seat(123, 2, "123", "1", "Normaal"),
                    new Seat(124, 2, "124", "1", "Normaal"),
                    new Seat(125, 2, "125", " ", " "),
                    new Seat(126, 2, "126", " ", " "),
                    new Seat(127, 2, "127", "1", "Normaal"),
                    new Seat(128, 2, "128", "1", "Normaal"),
                    new Seat(129, 2, "129", "2", "Normaal"),
                    new Seat(130, 2, "130", "2", "Normaal"),
                    new Seat(131, 2, "131", "2", "Normaal"),
                    new Seat(132, 2, "132", "2", "Normaal"),
                    new Seat(133, 2, "133", "3", "Normaal"),
                    new Seat(134, 2, "134", "3", "Normaal"),
                    new Seat(135, 2, "135", "3", "Normaal"),
                    new Seat(136, 2, "136", "3", "Normaal"),
                    new Seat(137, 2, "137", "2", "Normaal"),
                    new Seat(138, 2, "138", "2", "Normaal"),
                    new Seat(139, 2, "139", "2", "Normaal"),
                    new Seat(140, 2, "140", "2", "Normaal"),
                    new Seat(141, 2, "141", "1", "Normaal"),
                    new Seat(142, 2, "142", "1", "Normaal"),
                    new Seat(143, 2, "143", " ", " "),
                    new Seat(144, 2, "144", "1", "Normaal"),
                    new Seat(145, 2, "145", "1", "Normaal"),
                    new Seat(146, 2, "146", "2", "Normaal"),
                    new Seat(147, 2, "147", "2", "Normaal"),
                    new Seat(148, 2, "148", "2", "Normaal"),
                    new Seat(149, 2, "149", "2", "Normaal"),
                    new Seat(150, 2, "150", "3", "Normaal"),
                    new Seat(151, 2, "151", "3", "Normaal"),
                    new Seat(152, 2, "152", "3", "Normaal"),
                    new Seat(153, 2, "153", "3", "Normaal"),
                    new Seat(154, 2, "154", "3", "Normaal"),
                    new Seat(155, 2, "155", "3", "Normaal"),
                    new Seat(156, 2, "156", "2", "Normaal"),
                    new Seat(157, 2, "157", "2", "Normaal"),
                    new Seat(158, 2, "158", "2", "Normaal"),
                    new Seat(159, 2, "159", "2", "Normaal"),
                    new Seat(160, 2, "160", "1", "Normaal"),
                    new Seat(161, 2, "161", "1", "Normaal"),
                    new Seat(162, 2, "162", "1", "Normaal"),
                    new Seat(163, 2, "163", "1", "Normaal"),
                    new Seat(164, 2, "164", "2", "Normaal"),
                    new Seat(165, 2, "165", "2", "Normaal"),
                    new Seat(166, 2, "166", "2", "Normaal"),
                    new Seat(167, 2, "167", "2", "Normaal"),
                    new Seat(168, 2, "168", "3", "Normaal"),
                    new Seat(169, 2, "169", "3", "Normaal"),
                    new Seat(170, 2, "170", "3", "Normaal"),
                    new Seat(171, 2, "171", "3", "Normaal"),
                    new Seat(172, 2, "172", "3", "Normaal"),
                    new Seat(173, 2, "173", "3", "Normaal"),
                    new Seat(174, 2, "174", "2", "Normaal"),
                    new Seat(175, 2, "175", "2", "Normaal"),
                    new Seat(176, 2, "176", "2", "Normaal"),
                    new Seat(177, 2, "177", "2", "Normaal"),
                    new Seat(178, 2, "178", "1", "Normaal"),
                    new Seat(179, 2, "179", "1", "Normaal"),
                    new Seat(180, 2, "180", "1", "Normaal"),
                    new Seat(181, 2, "181", "1", "Normaal"),
                    new Seat(182, 2, "182", "2", "Normaal"),
                    new Seat(183, 2, "183", "2", "Normaal"),
                    new Seat(184, 2, "184", "2", "Normaal"),
                    new Seat(185, 2, "185", "2", "Normaal"),
                    new Seat(186, 2, "186", "3", "Normaal"),
                    new Seat(187, 2, "187", "3", "Normaal"),
                    new Seat(188, 2, "188", "3", "Normaal"),
                    new Seat(189, 2, "189", "3", "Normaal"),
                    new Seat(190, 2, "190", "3", "Normaal"),
                    new Seat(191, 2, "191", "3", "Normaal"),
                    new Seat(192, 2, "192", "2", "Normaal"),
                    new Seat(193, 2, "193", "2", "Normaal"),
                    new Seat(194, 2, "194", "2", "Normaal"),
                    new Seat(195, 2, "195", "2", "Normaal"),
                    new Seat(196, 2, "196", "1", "Normaal"),
                    new Seat(197, 2, "197", "1", "Normaal"),
                    new Seat(198, 2, "198", "1", "Normaal"),
                    new Seat(199, 2, "199", "1", "Normaal"),
                    new Seat(200, 2, "200", "1", "Normaal"),
                    new Seat(201, 2, "201", "2", "Normaal"),
                    new Seat(202, 2, "202", "2", "Normaal"),
                    new Seat(203, 2, "203", "2", "Normaal"),
                    new Seat(204, 2, "204", "3", "Normaal"),
                    new Seat(205, 2, "205", "3", "Normaal"),
                    new Seat(206, 2, "206", "3", "Normaal"),
                    new Seat(207, 2, "207", "3", "Normaal"),
                    new Seat(208, 2, "208", "3", "Normaal"),
                    new Seat(209, 2, "209", "3", "Normaal"),
                    new Seat(210, 2, "210", "2", "Normaal"),
                    new Seat(211, 2, "211", "2", "Normaal"),
                    new Seat(212, 2, "212", "2", "Normaal"),
                    new Seat(213, 2, "213", "1", "Normaal"),
                    new Seat(214, 2, "214", "1", "Normaal"),
                    new Seat(215, 2, "215", "1", "Normaal"),
                    new Seat(216, 2, "216", "1", "Normaal"),
                    new Seat(217, 2, "217", "1", "Normaal"),
                    new Seat(218, 2, "218", "1", "Normaal"),
                    new Seat(219, 2, "219", "2", "Normaal"),
                    new Seat(220, 2, "220", "2", "Normaal"),
                    new Seat(221, 2, "221", "2", "Normaal"),
                    new Seat(222, 2, "222", "2", "Normaal"),
                    new Seat(223, 2, "223", "3", "Normaal"),
                    new Seat(224, 2, "224", "3", "Normaal"),
                    new Seat(225, 2, "225", "3", "Normaal"),
                    new Seat(226, 2, "226", "3", "Normaal"),
                    new Seat(227, 2, "227", "2", "Normaal"),
                    new Seat(228, 2, "228", "2", "Normaal"),
                    new Seat(229, 2, "229", "2", "Normaal"),
                    new Seat(230, 2, "230", "2", "Normaal"),
                    new Seat(231, 2, "231", "1", "Normaal"),
                    new Seat(232, 2, "232", "1", "Normaal"),
                    new Seat(233, 2, "233", "1", "Normaal"),
                    new Seat(234, 2, "234", " ", " "),
                    new Seat(235, 2, "235", "1", "Normaal"),
                    new Seat(236, 2, "236", "1", "Normaal"),
                    new Seat(237, 2, "237", "1", "Normaal"),
                    new Seat(238, 2, "238", "2", "Normaal"),
                    new Seat(239, 2, "239", "2", "Normaal"),
                    new Seat(240, 2, "240", "2", "Normaal"),
                    new Seat(241, 2, "241", "2", "Normaal"),
                    new Seat(242, 2, "242", "3", "Normaal"),
                    new Seat(243, 2, "243", "3", "Normaal"),
                    new Seat(244, 2, "244", "2", "Normaal"),
                    new Seat(245, 2, "245", "2", "Normaal"),
                    new Seat(246, 2, "246", "2", "Normaal"),
                    new Seat(247, 2, "247", "2", "Normaal"),
                    new Seat(248, 2, "248", "1", "Normaal"),
                    new Seat(249, 2, "249", "1", "Normaal"),
                    new Seat(250, 2, "250", "1", "Normaal"),
                    new Seat(251, 2, "251", " ", " "),
                    new Seat(252, 2, "252", " ", " "),
                    new Seat(253, 2, "253", "1", "Normaal"),
                    new Seat(254, 2, "254", "1", "Normaal"),
                    new Seat(255, 2, "255", "1", "Normaal"),
                    new Seat(256, 2, "256", "2", "Normaal"),
                    new Seat(257, 2, "257", "2", "Normaal"),
                    new Seat(258, 2, "258", "2", "Normaal"),
                    new Seat(259, 2, "259", "2", "Normaal"),
                    new Seat(260, 2, "260", "2", "Normaal"),
                    new Seat(261, 2, "261", "2", "Normaal"),
                    new Seat(262, 2, "262", "2", "Normaal"),
                    new Seat(263, 2, "263", "2", "Normaal"),
                    new Seat(264, 2, "264", "2", "Normaal"),
                    new Seat(265, 2, "265", "2", "Normaal"),
                    new Seat(266, 2, "266", "1", "Normaal"),
                    new Seat(267, 2, "267", "1", "Normaal"),
                    new Seat(268, 2, "268", "1", "Normaal"),
                    new Seat(269, 2, "269", " ", " "),
                    new Seat(270, 2, "270", " ", " "),
                    new Seat(271, 2, "271", "1", "Normaal"),
                    new Seat(272, 2, "272", "1", "Normaal"),
                    new Seat(273, 2, "273", "1", "Normaal"),
                    new Seat(274, 2, "274", "1", "Normaal"),
                    new Seat(275, 2, "275", "2", "Normaal"),
                    new Seat(276, 2, "276", "2", "Normaal"),
                    new Seat(277, 2, "277", "2", "Normaal"),
                    new Seat(278, 2, "278", "2", "Normaal"),
                    new Seat(279, 2, "279", "2", "Normaal"),
                    new Seat(280, 2, "280", "2", "Normaal"),
                    new Seat(281, 2, "281", "2", "Normaal"),
                    new Seat(282, 2, "282", "2", "Normaal"),
                    new Seat(283, 2, "283", "1", "Normaal"),
                    new Seat(284, 2, "284", "1", "Normaal"),
                    new Seat(285, 2, "285", "1", "Normaal"),
                    new Seat(286, 2, "286", "1", "Normaal"),
                    new Seat(287, 2, "287", " ", " "),
                    new Seat(288, 2, "288", " ", " "),
                    new Seat(289, 2, "289", "1", "Normaal"),
                    new Seat(290, 2, "290", "1", "Normaal"),
                    new Seat(291, 2, "291", "1", "Normaal"),
                    new Seat(292, 2, "292", "1", "Normaal"),
                    new Seat(293, 2, "293", "2", "Normaal"),
                    new Seat(294, 2, "294", "2", "Normaal"),
                    new Seat(295, 2, "295", "2", "Normaal"),
                    new Seat(296, 2, "296", "2", "Normaal"),
                    new Seat(297, 2, "297", "2", "Normaal"),
                    new Seat(298, 2, "298", "2", "Normaal"),
                    new Seat(299, 2, "299", "2", "Normaal"),
                    new Seat(300, 2, "300", "2", "Normaal"),
                    new Seat(301, 2, "301", "1", "Normaal"),
                    new Seat(302, 2, "302", "1", "Normaal"),
                    new Seat(303, 2, "303", "1", "Normaal"),
                    new Seat(304, 2, "304", "1", "Normaal"),
                    new Seat(305, 2, "305", " ", " "),
                    new Seat(306, 2, "306", " ", " "),
                    new Seat(307, 2, "307", "1", "Normaal"),
                    new Seat(308, 2, "308", "1", "Normaal"),
                    new Seat(309, 2, "309", "1", "Normaal"),
                    new Seat(310, 2, "310", "1", "Normaal"),
                    new Seat(311, 2, "311", "1", "Normaal"),
                    new Seat(312, 2, "312", "2", "Normaal"),
                    new Seat(313, 2, "313", "2", "Normaal"),
                    new Seat(314, 2, "314", "2", "Normaal"),
                    new Seat(315, 2, "315", "2", "Normaal"),
                    new Seat(316, 2, "316", "2", "Normaal"),
                    new Seat(317, 2, "317", "2", "Normaal"),
                    new Seat(318, 2, "318", "1", "Normaal"),
                    new Seat(319, 2, "319", "1", "Normaal"),
                    new Seat(320, 2, "320", "1", "Normaal"),
                    new Seat(321, 2, "321", "1", "Normaal"),
                    new Seat(322, 2, "322", "1", "Normaal"),
                    new Seat(323, 2, "323", " ", " "),
                    new Seat(324, 2, "324", " ", " "),
                    new Seat(325, 2, "325", "1", "Normaal"),
                    new Seat(326, 2, "326", "1", "Normaal"),
                    new Seat(327, 2, "327", "1", "Normaal"),
                    new Seat(328, 2, "328", "1", "Normaal"),
                    new Seat(329, 2, "329", "1", "Normaal"),
                    new Seat(330, 2, "330", "1", "Normaal"),
                    new Seat(331, 2, "331", "1", "Normaal"),
                    new Seat(332, 2, "332", "1", "Normaal"),
                    new Seat(333, 2, "333", "1", "Normaal"),
                    new Seat(334, 2, "334", "1", "Normaal"),
                    new Seat(335, 2, "335", "1", "Normaal"),
                    new Seat(336, 2, "336", "1", "Normaal"),
                    new Seat(337, 2, "337", "1", "Normaal"),
                    new Seat(338, 2, "338", "1", "Normaal"),
                    new Seat(339, 2, "339", "1", "Normaal"),
                    new Seat(340, 2, "340", "1", "Normaal"),
                    new Seat(341, 2, "341", " ", " ")
                };
                List<Seat> layout3 = new List<Seat> {
                    new Seat(0, 3, "0", " ", " "),
                    new Seat(1, 3, "1", " ", " "),
                    new Seat(2, 3, "2", " ", " "),
                    new Seat(3, 3, "3", " ", " "),
                    new Seat(4, 3, "4", " ", " "),
                    new Seat(5, 3, "5", " ", " "),
                    new Seat(6, 3, "6", " ", " "),
                    new Seat(7, 3, "7", " ", " "),
                    new Seat(8, 3, "8", "1", "Normaal"),
                    new Seat(9, 3, "9", "1", "Normaal"),
                    new Seat(10, 3, "10", "1", "Normaal"),
                    new Seat(11, 3, "11", "1", "Normaal"),
                    new Seat(12, 3, "12", "1", "Normaal"),
                    new Seat(13, 3, "13", "1", "Normaal"),
                    new Seat(14, 3, "14", "1", "Normaal"),
                    new Seat(15, 3, "15", "1", "Normaal"),
                    new Seat(16, 3, "16", "1", "Normaal"),
                    new Seat(17, 3, "17", "1", "Normaal"),
                    new Seat(18, 3, "18", "1", "Normaal"),
                    new Seat(19, 3, "19", "1", "Normaal"),
                    new Seat(20, 3, "20", "1", "Normaal"),
                    new Seat(21, 3, "21", "1", "Normaal"),
                    new Seat(22, 3, "22", " ", " "),
                    new Seat(23, 3, "23", " ", " "),
                    new Seat(24, 3, "24", " ", " "),
                    new Seat(25, 3, "25", " ", " "),
                    new Seat(26, 3, "26", " ", " "),
                    new Seat(27, 3, "27", " ", " "),
                    new Seat(28, 3, "28", " ", " "),
                    new Seat(29, 3, "29", " ", " "),
                    new Seat(30, 3, "30", " ", " "),
                    new Seat(31, 3, "31", " ", " "),
                    new Seat(32, 3, "32", " ", " "),
                    new Seat(33, 3, "33", " ", " "),
                    new Seat(34, 3, "34", " ", " "),
                    new Seat(35, 3, "35", " ", " "),
                    new Seat(36, 3, "36", " ", " "),
                    new Seat(37, 3, "37", "1", "Normaal"),
                    new Seat(38, 3, "38", "1", "Normaal"),
                    new Seat(39, 3, "39", "1", "Normaal"),
                    new Seat(40, 3, "40", "1", "Normaal"),
                    new Seat(41, 3, "41", "1", "Normaal"),
                    new Seat(42, 3, "42", "1", "Normaal"),
                    new Seat(43, 3, "43", "1", "Normaal"),
                    new Seat(44, 3, "44", "1", "Normaal"),
                    new Seat(45, 3, "45", "1", "Normaal"),
                    new Seat(46, 3, "46", "1", "Normaal"),
                    new Seat(47, 3, "47", "1", "Normaal"),
                    new Seat(48, 3, "48", "1", "Normaal"),
                    new Seat(49, 3, "49", "1", "Normaal"),
                    new Seat(50, 3, "50", "1", "Normaal"),
                    new Seat(51, 3, "51", "1", "Normaal"),
                    new Seat(52, 3, "52", "1", "Normaal"),
                    new Seat(53, 3, "53", " ", " "),
                    new Seat(54, 3, "54", " ", " "),
                    new Seat(55, 3, "55", " ", " "),
                    new Seat(56, 3, "56", " ", " "),
                    new Seat(57, 3, "57", " ", " "),
                    new Seat(58, 3, "58", " ", " "),
                    new Seat(59, 3, "59", " ", " "),
                    new Seat(60, 3, "60", " ", " "),
                    new Seat(61, 3, "61", " ", " "),
                    new Seat(62, 3, "62", " ", " "),
                    new Seat(63, 3, "63", " ", " "),
                    new Seat(64, 3, "64", " ", " "),
                    new Seat(65, 3, "65", "1", "Normaal"),
                    new Seat(66, 3, "66", "1", "Normaal"),
                    new Seat(67, 3, "67", "1", "Normaal"),
                    new Seat(68, 3, "68", "1", "Normaal"),
                    new Seat(69, 3, "69", "1", "Normaal"),
                    new Seat(70, 3, "70", "1", "Normaal"),
                    new Seat(71, 3, "71", "1", "Normaal"),
                    new Seat(72, 3, "72", "1", "Normaal"),
                    new Seat(73, 3, "73", "1", "Normaal"),
                    new Seat(74, 3, "74", "1", "Normaal"),
                    new Seat(75, 3, "75", "1", "Normaal"),
                    new Seat(76, 3, "76", "1", "Normaal"),
                    new Seat(77, 3, "77", "1", "Normaal"),
                    new Seat(78, 3, "78", "1", "Normaal"),
                    new Seat(79, 3, "79", "1", "Normaal"),
                    new Seat(80, 3, "80", "1", "Normaal"),
                    new Seat(81, 3, "81", "1", "Normaal"),
                    new Seat(82, 3, "82", "1", "Normaal"),
                    new Seat(83, 3, "83", "1", "Normaal"),
                    new Seat(84, 3, "84", "1", "Normaal"),
                    new Seat(85, 3, "85", " ", " "),
                    new Seat(86, 3, "86", " ", " "),
                    new Seat(87, 3, "87", " ", " "),
                    new Seat(88, 3, "88", " ", " "),
                    new Seat(89, 3, "89", " ", " "),
                    new Seat(90, 3, "90", " ", " "),
                    new Seat(91, 3, "91", " ", " "),
                    new Seat(92, 3, "92", " ", " "),
                    new Seat(93, 3, "93", "1", "Normaal"),
                    new Seat(94, 3, "94", "1", "Normaal"),
                    new Seat(95, 3, "95", "1", "Normaal"),
                    new Seat(96, 3, "96", "1", "Normaal"),
                    new Seat(97, 3, "97", "1", "Normaal"),
                    new Seat(98, 3, "98", "1", "Normaal"),
                    new Seat(99, 3, "99", "1", "Normaal"),
                    new Seat(100, 3, "100", "1", "Normaal"),
                    new Seat(101, 3, "101", "1", "Normaal"),
                    new Seat(102, 3, "102", "2", "Normaal"),
                    new Seat(103, 3, "103", "2", "Normaal"),
                    new Seat(104, 3, "104", "2", "Normaal"),
                    new Seat(105, 3, "105", "2", "Normaal"),
                    new Seat(106, 3, "106", "2", "Normaal"),
                    new Seat(107, 3, "107", "2", "Normaal"),
                    new Seat(108, 3, "108", "1", "Normaal"),
                    new Seat(109, 3, "109", "1", "Normaal"),
                    new Seat(110, 3, "110", "1", "Normaal"),
                    new Seat(111, 3, "111", "1", "Normaal"),
                    new Seat(112, 3, "112", "1", "Normaal"),
                    new Seat(113, 3, "113", "1", "Normaal"),
                    new Seat(114, 3, "114", "1", "Normaal"),
                    new Seat(115, 3, "115", "1", "Normaal"),
                    new Seat(116, 3, "116", "1", "Normaal"),
                    new Seat(117, 3, "117", " ", " "),
                    new Seat(118, 3, "118", " ", " "),
                    new Seat(119, 3, "119", " ", " "),
                    new Seat(120, 3, "120", " ", " "),
                    new Seat(121, 3, "121", " ", " "),
                    new Seat(122, 3, "122", " ", " "),
                    new Seat(123, 3, "123", "1", "Normaal"),
                    new Seat(124, 3, "124", "1", "Normaal"),
                    new Seat(125, 3, "125", "1", "Normaal"),
                    new Seat(126, 3, "126", "1", "Normaal"),
                    new Seat(127, 3, "127", "1", "Normaal"),
                    new Seat(128, 3, "128", "1", "Normaal"),
                    new Seat(129, 3, "129", "1", "Normaal"),
                    new Seat(130, 3, "130", "2", "Normaal"),
                    new Seat(131, 3, "131", "2", "Normaal"),
                    new Seat(132, 3, "132", "2", "Normaal"),
                    new Seat(133, 3, "133", "2", "Normaal"),
                    new Seat(134, 3, "134", "2", "Normaal"),
                    new Seat(135, 3, "135", "2", "Normaal"),
                    new Seat(136, 3, "136", "2", "Normaal"),
                    new Seat(137, 3, "137", "2", "Normaal"),
                    new Seat(138, 3, "138", "2", "Normaal"),
                    new Seat(139, 3, "139", "2", "Normaal"),
                    new Seat(140, 3, "140", "1", "Normaal"),
                    new Seat(141, 3, "141", "1", "Normaal"),
                    new Seat(142, 3, "142", "1", "Normaal"),
                    new Seat(143, 3, "143", "1", "Normaal"),
                    new Seat(144, 3, "144", "1", "Normaal"),
                    new Seat(145, 3, "145", "1", "Normaal"),
                    new Seat(146, 3, "146", "1", "Normaal"),
                    new Seat(147, 3, "147", " ", " "),
                    new Seat(148, 3, "148", " ", " "),
                    new Seat(149, 3, "149", " ", " "),
                    new Seat(150, 3, "150", " ", " "),
                    new Seat(151, 3, "151", " ", " "),
                    new Seat(152, 3, "152", "1", "Normaal"),
                    new Seat(153, 3, "153", "1", "Normaal"),
                    new Seat(154, 3, "154", "1", "Normaal"),
                    new Seat(155, 3, "155", "1", "Normaal"),
                    new Seat(156, 3, "156", "1", "Normaal"),
                    new Seat(157, 3, "157", "1", "Normaal"),
                    new Seat(158, 3, "158", "1", "Normaal"),
                    new Seat(159, 3, "159", "2", "Normaal"),
                    new Seat(160, 3, "160", "2", "Normaal"),
                    new Seat(161, 3, "161", "2", "Normaal"),
                    new Seat(162, 3, "162", "2", "Normaal"),
                    new Seat(163, 3, "163", "2", "Normaal"),
                    new Seat(164, 3, "164", "2", "Normaal"),
                    new Seat(165, 3, "165", "2", "Normaal"),
                    new Seat(166, 3, "166", "2", "Normaal"),
                    new Seat(167, 3, "167", "2", "Normaal"),
                    new Seat(168, 3, "168", "2", "Normaal"),
                    new Seat(169, 3, "169", "2", "Normaal"),
                    new Seat(170, 3, "170", "2", "Normaal"),
                    new Seat(171, 3, "171", "1", "Normaal"),
                    new Seat(172, 3, "172", "1", "Normaal"),
                    new Seat(173, 3, "173", "1", "Normaal"),
                    new Seat(174, 3, "174", "1", "Normaal"),
                    new Seat(175, 3, "175", "1", "Normaal"),
                    new Seat(176, 3, "176", "1", "Normaal"),
                    new Seat(177, 3, "177", "1", "Normaal"),
                    new Seat(178, 3, "178", " ", " "),
                    new Seat(179, 3, "179", " ", " "),
                    new Seat(180, 3, "180", " ", " "),
                    new Seat(181, 3, "181", " ", " "),
                    new Seat(182, 3, "182", "1", "Normaal"),
                    new Seat(183, 3, "183", "1", "Normaal"),
                    new Seat(184, 3, "184", "1", "Normaal"),
                    new Seat(185, 3, "185", "1", "Normaal"),
                    new Seat(186, 3, "186", "1", "Normaal"),
                    new Seat(187, 3, "187", "1", "Normaal"),
                    new Seat(188, 3, "188", "2", "Normaal"),
                    new Seat(189, 3, "189", "2", "Normaal"),
                    new Seat(190, 3, "190", "2", "Normaal"),
                    new Seat(191, 3, "191", "2", "Normaal"),
                    new Seat(192, 3, "192", "2", "Normaal"),
                    new Seat(193, 3, "193", "2", "Normaal"),
                    new Seat(194, 3, "194", "2", "Normaal"),
                    new Seat(195, 3, "195", "2", "Normaal"),
                    new Seat(196, 3, "196", "2", "Normaal"),
                    new Seat(197, 3, "197", "2", "Normaal"),
                    new Seat(198, 3, "198", "2", "Normaal"),
                    new Seat(199, 3, "199", "2", "Normaal"),
                    new Seat(200, 3, "200", "2", "Normaal"),
                    new Seat(201, 3, "201", "2", "Normaal"),
                    new Seat(202, 3, "202", "1", "Normaal"),
                    new Seat(203, 3, "203", "1", "Normaal"),
                    new Seat(204, 3, "204", "1", "Normaal"),
                    new Seat(205, 3, "205", "1", "Normaal"),
                    new Seat(206, 3, "206", "1", "Normaal"),
                    new Seat(207, 3, "207", "1", "Normaal"),
                    new Seat(208, 3, "208", " ", " "),
                    new Seat(209, 3, "209", " ", " "),
                    new Seat(210, 3, "210", " ", " "),
                    new Seat(211, 3, "211", "1", "Normaal"),
                    new Seat(212, 3, "212", "1", "Normaal"),
                    new Seat(213, 3, "213", "1", "Normaal"),
                    new Seat(214, 3, "214", "1", "Normaal"),
                    new Seat(215, 3, "215", "1", "Normaal"),
                    new Seat(216, 3, "216", "1", "Normaal"),
                    new Seat(217, 3, "217", "1", "Normaal"),
                    new Seat(218, 3, "218", "2", "Normaal"),
                    new Seat(219, 3, "219", "2", "Normaal"),
                    new Seat(220, 3, "220", "2", "Normaal"),
                    new Seat(221, 3, "221", "2", "Normaal"),
                    new Seat(222, 3, "222", "2", "Normaal"),
                    new Seat(223, 3, "223", "3", "Normaal"),
                    new Seat(224, 3, "224", "3", "Normaal"),
                    new Seat(225, 3, "225", "3", "Normaal"),
                    new Seat(226, 3, "226", "3", "Normaal"),
                    new Seat(227, 3, "227", "2", "Normaal"),
                    new Seat(228, 3, "228", "2", "Normaal"),
                    new Seat(229, 3, "229", "2", "Normaal"),
                    new Seat(230, 3, "230", "2", "Normaal"),
                    new Seat(231, 3, "231", "2", "Normaal"),
                    new Seat(232, 3, "232", "1", "Normaal"),
                    new Seat(233, 3, "233", "1", "Normaal"),
                    new Seat(234, 3, "234", "1", "Normaal"),
                    new Seat(235, 3, "235", "1", "Normaal"),
                    new Seat(236, 3, "236", "1", "Normaal"),
                    new Seat(237, 3, "237", "1", "Normaal"),
                    new Seat(238, 3, "238", "1", "Normaal"),
                    new Seat(239, 3, "239", " ", " "),
                    new Seat(240, 3, "240", "1", "Normaal"),
                    new Seat(241, 3, "241", "1", "Normaal"),
                    new Seat(242, 3, "242", "1", "Normaal"),
                    new Seat(243, 3, "243", "1", "Normaal"),
                    new Seat(244, 3, "244", "1", "Normaal"),
                    new Seat(245, 3, "245", "1", "Normaal"),
                    new Seat(246, 3, "246", "1", "Normaal"),
                    new Seat(247, 3, "247", "2", "Normaal"),
                    new Seat(248, 3, "248", "2", "Normaal"),
                    new Seat(249, 3, "249", "2", "Normaal"),
                    new Seat(250, 3, "250", "2", "Normaal"),
                    new Seat(251, 3, "251", "3", "Normaal"),
                    new Seat(252, 3, "252", "3", "Normaal"),
                    new Seat(253, 3, "253", "3", "Normaal"),
                    new Seat(254, 3, "254", "3", "Normaal"),
                    new Seat(255, 3, "255", "3", "Normaal"),
                    new Seat(256, 3, "256", "3", "Normaal"),
                    new Seat(257, 3, "257", "3", "Normaal"),
                    new Seat(258, 3, "258", "3", "Normaal"),
                    new Seat(259, 3, "259", "2", "Normaal"),
                    new Seat(260, 3, "260", "2", "Normaal"),
                    new Seat(261, 3, "261", "2", "Normaal"),
                    new Seat(262, 3, "262", "2", "Normaal"),
                    new Seat(263, 3, "263", "1", "Normaal"),
                    new Seat(264, 3, "264", "1", "Normaal"),
                    new Seat(265, 3, "265", "1", "Normaal"),
                    new Seat(266, 3, "266", "1", "Normaal"),
                    new Seat(267, 3, "267", "1", "Normaal"),
                    new Seat(268, 3, "268", "1", "Normaal"),
                    new Seat(269, 3, "269", "1", "Normaal"),
                    new Seat(270, 3, "270", "1", "Normaal"),
                    new Seat(271, 3, "271", "1", "Normaal"),
                    new Seat(272, 3, "272", "1", "Normaal"),
                    new Seat(273, 3, "273", "1", "Normaal"),
                    new Seat(274, 3, "274", "1", "Normaal"),
                    new Seat(275, 3, "275", "1", "Normaal"),
                    new Seat(276, 3, "276", "2", "Normaal"),
                    new Seat(277, 3, "277", "2", "Normaal"),
                    new Seat(278, 3, "278", "2", "Normaal"),
                    new Seat(279, 3, "279", "2", "Normaal"),
                    new Seat(280, 3, "280", "2", "Normaal"),
                    new Seat(281, 3, "281", "3", "Normaal"),
                    new Seat(282, 3, "282", "3", "Normaal"),
                    new Seat(283, 3, "283", "3", "Normaal"),
                    new Seat(284, 3, "284", "3", "Normaal"),
                    new Seat(285, 3, "285", "3", "Normaal"),
                    new Seat(286, 3, "286", "3", "Normaal"),
                    new Seat(287, 3, "287", "3", "Normaal"),
                    new Seat(288, 3, "288", "3", "Normaal"),
                    new Seat(289, 3, "289", "2", "Normaal"),
                    new Seat(290, 3, "290", "2", "Normaal"),
                    new Seat(291, 3, "291", "2", "Normaal"),
                    new Seat(292, 3, "292", "2", "Normaal"),
                    new Seat(293, 3, "293", "2", "Normaal"),
                    new Seat(294, 3, "294", "1", "Normaal"),
                    new Seat(295, 3, "295", "1", "Normaal"),
                    new Seat(296, 3, "296", "1", "Normaal"),
                    new Seat(297, 3, "297", "1", "Normaal"),
                    new Seat(298, 3, "298", "1", "Normaal"),
                    new Seat(299, 3, "299", "1", "Normaal"),
                    new Seat(300, 3, "300", "1", "Normaal"),
                    new Seat(301, 3, "301", "1", "Normaal"),
                    new Seat(302, 3, "302", "1", "Normaal"),
                    new Seat(303, 3, "303", "1", "Normaal"),
                    new Seat(304, 3, "304", "1", "Normaal"),
                    new Seat(305, 3, "305", "2", "Normaal"),
                    new Seat(306, 3, "306", "2", "Normaal"),
                    new Seat(307, 3, "307", "2", "Normaal"),
                    new Seat(308, 3, "308", "2", "Normaal"),
                    new Seat(309, 3, "309", "2", "Normaal"),
                    new Seat(310, 3, "310", "2", "Normaal"),
                    new Seat(311, 3, "311", "3", "Normaal"),
                    new Seat(312, 3, "312", "3", "Normaal"),
                    new Seat(313, 3, "313", "3", "Normaal"),
                    new Seat(314, 3, "314", "3", "Normaal"),
                    new Seat(315, 3, "315", "3", "Normaal"),
                    new Seat(316, 3, "316", "3", "Normaal"),
                    new Seat(317, 3, "317", "3", "Normaal"),
                    new Seat(318, 3, "318", "3", "Normaal"),
                    new Seat(319, 3, "319", "2", "Normaal"),
                    new Seat(320, 3, "320", "2", "Normaal"),
                    new Seat(321, 3, "321", "2", "Normaal"),
                    new Seat(322, 3, "322", "2", "Normaal"),
                    new Seat(323, 3, "323", "2", "Normaal"),
                    new Seat(324, 3, "324", "2", "Normaal"),
                    new Seat(325, 3, "325", "1", "Normaal"),
                    new Seat(326, 3, "326", "1", "Normaal"),
                    new Seat(327, 3, "327", "1", "Normaal"),
                    new Seat(328, 3, "328", "1", "Normaal"),
                    new Seat(329, 3, "329", "1", "Normaal"),
                    new Seat(330, 3, "330", "1", "Normaal"),
                    new Seat(331, 3, "331", "1", "Normaal"),
                    new Seat(332, 3, "332", "1", "Normaal"),
                    new Seat(333, 3, "333", "1", "Normaal"),
                    new Seat(334, 3, "334", "1", "Normaal"),
                    new Seat(335, 3, "335", "2", "Normaal"),
                    new Seat(336, 3, "336", "2", "Normaal"),
                    new Seat(337, 3, "337", "2", "Normaal"),
                    new Seat(338, 3, "338", "2", "Normaal"),
                    new Seat(339, 3, "339", "2", "Normaal"),
                    new Seat(340, 3, "340", "2", "Normaal"),
                    new Seat(341, 3, "341", "3", "Normaal"),
                    new Seat(342, 3, "342", "3", "Normaal"),
                    new Seat(343, 3, "343", "3", "Normaal"),
                    new Seat(344, 3, "344", "3", "Normaal"),
                    new Seat(345, 3, "345", "3", "Normaal"),
                    new Seat(346, 3, "346", "3", "Normaal"),
                    new Seat(347, 3, "347", "3", "Normaal"),
                    new Seat(348, 3, "348", "3", "Normaal"),
                    new Seat(349, 3, "349", "2", "Normaal"),
                    new Seat(350, 3, "350", "2", "Normaal"),
                    new Seat(351, 3, "351", "2", "Normaal"),
                    new Seat(352, 3, "352", "2", "Normaal"),
                    new Seat(353, 3, "353", "2", "Normaal"),
                    new Seat(354, 3, "354", "2", "Normaal"),
                    new Seat(355, 3, "355", "1", "Normaal"),
                    new Seat(356, 3, "356", "1", "Normaal"),
                    new Seat(357, 3, "357", "1", "Normaal"),
                    new Seat(358, 3, "358", "1", "Normaal"),
                    new Seat(359, 3, "359", "1", "Normaal"),
                    new Seat(360, 3, "360", "1", "Normaal"),
                    new Seat(361, 3, "361", "1", "Normaal"),
                    new Seat(362, 3, "362", "1", "Normaal"),
                    new Seat(363, 3, "363", "1", "Normaal"),
                    new Seat(364, 3, "364", "1", "Normaal"),
                    new Seat(365, 3, "365", "1", "Normaal"),
                    new Seat(366, 3, "366", "2", "Normaal"),
                    new Seat(367, 3, "367", "2", "Normaal"),
                    new Seat(368, 3, "368", "2", "Normaal"),
                    new Seat(369, 3, "369", "2", "Normaal"),
                    new Seat(370, 3, "370", "2", "Normaal"),
                    new Seat(371, 3, "371", "3", "Normaal"),
                    new Seat(372, 3, "372", "3", "Normaal"),
                    new Seat(373, 3, "373", "3", "Normaal"),
                    new Seat(374, 3, "374", "3", "Normaal"),
                    new Seat(375, 3, "375", "3", "Normaal"),
                    new Seat(376, 3, "376", "3", "Normaal"),
                    new Seat(377, 3, "377", "3", "Normaal"),
                    new Seat(378, 3, "378", "3", "Normaal"),
                    new Seat(379, 3, "379", "2", "Normaal"),
                    new Seat(380, 3, "380", "2", "Normaal"),
                    new Seat(381, 3, "381", "2", "Normaal"),
                    new Seat(382, 3, "382", "2", "Normaal"),
                    new Seat(383, 3, "383", "2", "Normaal"),
                    new Seat(384, 3, "384", "1", "Normaal"),
                    new Seat(385, 3, "385", "1", "Normaal"),
                    new Seat(386, 3, "386", "1", "Normaal"),
                    new Seat(387, 3, "387", "1", "Normaal"),
                    new Seat(388, 3, "388", "1", "Normaal"),
                    new Seat(389, 3, "389", "1", "Normaal"),
                    new Seat(390, 3, "390", " ", " "),
                    new Seat(391, 3, "391", "1", "Normaal"),
                    new Seat(392, 3, "392", "1", "Normaal"),
                    new Seat(393, 3, "393", "1", "Normaal"),
                    new Seat(394, 3, "394", "1", "Normaal"),
                    new Seat(395, 3, "395", "1", "Normaal"),
                    new Seat(396, 3, "396", "2", "Normaal"),
                    new Seat(397, 3, "397", "2", "Normaal"),
                    new Seat(398, 3, "398", "2", "Normaal"),
                    new Seat(399, 3, "399", "2", "Normaal"),
                    new Seat(400, 3, "400", "2", "Normaal"),
                    new Seat(401, 3, "401", "3", "Normaal"),
                    new Seat(402, 3, "402", "3", "Normaal"),
                    new Seat(403, 3, "403", "3", "Normaal"),
                    new Seat(404, 3, "404", "3", "Normaal"),
                    new Seat(405, 3, "405", "3", "Normaal"),
                    new Seat(406, 3, "406", "3", "Normaal"),
                    new Seat(407, 3, "407", "3", "Normaal"),
                    new Seat(408, 3, "408", "3", "Normaal"),
                    new Seat(409, 3, "409", "2", "Normaal"),
                    new Seat(410, 3, "410", "2", "Normaal"),
                    new Seat(411, 3, "411", "2", "Normaal"),
                    new Seat(412, 3, "412", "2", "Normaal"),
                    new Seat(413, 3, "413", "2", "Normaal"),
                    new Seat(414, 3, "414", "1", "Normaal"),
                    new Seat(415, 3, "415", "1", "Normaal"),
                    new Seat(416, 3, "416", "1", "Normaal"),
                    new Seat(417, 3, "417", "1", "Normaal"),
                    new Seat(418, 3, "418", "1", "Normaal"),
                    new Seat(419, 3, "419", " ", " "),
                    new Seat(420, 3, "420", " ", " "),
                    new Seat(421, 3, "421", " ", " "),
                    new Seat(422, 3, "422", "1", "Normaal"),
                    new Seat(423, 3, "423", "1", "Normaal"),
                    new Seat(424, 3, "424", "1", "Normaal"),
                    new Seat(425, 3, "425", "1", "Normaal"),
                    new Seat(426, 3, "426", "1", "Normaal"),
                    new Seat(427, 3, "427", "2", "Normaal"),
                    new Seat(428, 3, "428", "2", "Normaal"),
                    new Seat(429, 3, "429", "2", "Normaal"),
                    new Seat(430, 3, "430", "2", "Normaal"),
                    new Seat(431, 3, "431", "2", "Normaal"),
                    new Seat(432, 3, "432", "3", "Normaal"),
                    new Seat(433, 3, "433", "3", "Normaal"),
                    new Seat(434, 3, "434", "3", "Normaal"),
                    new Seat(435, 3, "435", "3", "Normaal"),
                    new Seat(436, 3, "436", "3", "Normaal"),
                    new Seat(437, 3, "437", "3", "Normaal"),
                    new Seat(438, 3, "438", "2", "Normaal"),
                    new Seat(439, 3, "439", "2", "Normaal"),
                    new Seat(440, 3, "440", "2", "Normaal"),
                    new Seat(441, 3, "441", "2", "Normaal"),
                    new Seat(442, 3, "442", "2", "Normaal"),
                    new Seat(443, 3, "443", "1", "Normaal"),
                    new Seat(444, 3, "444", "1", "Normaal"),
                    new Seat(445, 3, "445", "1", "Normaal"),
                    new Seat(446, 3, "446", "1", "Normaal"),
                    new Seat(447, 3, "447", "1", "Normaal"),
                    new Seat(448, 3, "448", " ", " "),
                    new Seat(449, 3, "449", " ", " "),
                    new Seat(450, 3, "450", " ", " "),
                    new Seat(451, 3, "451", " ", " "),
                    new Seat(452, 3, "452", " ", " "),
                    new Seat(453, 3, "453", "1", "Normaal"),
                    new Seat(454, 3, "454", "1", "Normaal"),
                    new Seat(455, 3, "455", "1", "Normaal"),
                    new Seat(456, 3, "456", "1", "Normaal"),
                    new Seat(457, 3, "457", "2", "Normaal"),
                    new Seat(458, 3, "458", "2", "Normaal"),
                    new Seat(459, 3, "459", "2", "Normaal"),
                    new Seat(460, 3, "460", "2", "Normaal"),
                    new Seat(461, 3, "461", "2", "Normaal"),
                    new Seat(462, 3, "462", "2", "Normaal"),
                    new Seat(463, 3, "463", "3", "Normaal"),
                    new Seat(464, 3, "464", "3", "Normaal"),
                    new Seat(465, 3, "465", "3", "Normaal"),
                    new Seat(466, 3, "466", "3", "Normaal"),
                    new Seat(467, 3, "467", "2", "Normaal"),
                    new Seat(468, 3, "468", "2", "Normaal"),
                    new Seat(469, 3, "469", "2", "Normaal"),
                    new Seat(470, 3, "470", "2", "Normaal"),
                    new Seat(471, 3, "471", "2", "Normaal"),
                    new Seat(472, 3, "472", "2", "Normaal"),
                    new Seat(473, 3, "473", "1", "Normaal"),
                    new Seat(474, 3, "474", "1", "Normaal"),
                    new Seat(475, 3, "475", "1", "Normaal"),
                    new Seat(476, 3, "476", "1", "Normaal"),
                    new Seat(477, 3, "477", " ", " "),
                    new Seat(478, 3, "478", " ", " "),
                    new Seat(479, 3, "479", " ", " "),
                    new Seat(480, 3, "480", " ", " "),
                    new Seat(481, 3, "481", " ", " "),
                    new Seat(482, 3, "482", " ", " "),
                    new Seat(483, 3, "483", "1", "Normaal"),
                    new Seat(484, 3, "484", "1", "Normaal"),
                    new Seat(485, 3, "485", "1", "Normaal"),
                    new Seat(486, 3, "486", "1", "Normaal"),
                    new Seat(487, 3, "487", "1", "Normaal"),
                    new Seat(488, 3, "488", "2", "Normaal"),
                    new Seat(489, 3, "489", "2", "Normaal"),
                    new Seat(490, 3, "490", "2", "Normaal"),
                    new Seat(491, 3, "491", "2", "Normaal"),
                    new Seat(492, 3, "492", "2", "Normaal"),
                    new Seat(493, 3, "493", "2", "Normaal"),
                    new Seat(494, 3, "494", "2", "Normaal"),
                    new Seat(495, 3, "495", "2", "Normaal"),
                    new Seat(496, 3, "496", "2", "Normaal"),
                    new Seat(497, 3, "497", "2", "Normaal"),
                    new Seat(498, 3, "498", "2", "Normaal"),
                    new Seat(499, 3, "499", "2", "Normaal"),
                    new Seat(500, 3, "500", "2", "Normaal"),
                    new Seat(501, 3, "501", "2", "Normaal"),
                    new Seat(502, 3, "502", "1", "Normaal"),
                    new Seat(503, 3, "503", "1", "Normaal"),
                    new Seat(504, 3, "504", "1", "Normaal"),
                    new Seat(505, 3, "505", "1", "Normaal"),
                    new Seat(506, 3, "506", "1", "Normaal"),
                    new Seat(507, 3, "507", " ", " "),
                    new Seat(508, 3, "508", " ", " "),
                    new Seat(509, 3, "509", " ", " "),
                    new Seat(510, 3, "510", " ", " "),
                    new Seat(511, 3, "511", " ", " "),
                    new Seat(512, 3, "512", " ", " "),
                    new Seat(513, 3, "513", "1", "Normaal"),
                    new Seat(514, 3, "514", "1", "Normaal"),
                    new Seat(515, 3, "515", "1", "Normaal"),
                    new Seat(516, 3, "516", "1", "Normaal"),
                    new Seat(517, 3, "517", "1", "Normaal"),
                    new Seat(518, 3, "518", "2", "Normaal"),
                    new Seat(519, 3, "519", "2", "Normaal"),
                    new Seat(520, 3, "520", "2", "Normaal"),
                    new Seat(521, 3, "521", "2", "Normaal"),
                    new Seat(522, 3, "522", "2", "Normaal"),
                    new Seat(523, 3, "523", "2", "Normaal"),
                    new Seat(524, 3, "524", "2", "Normaal"),
                    new Seat(525, 3, "525", "2", "Normaal"),
                    new Seat(526, 3, "526", "2", "Normaal"),
                    new Seat(527, 3, "527", "2", "Normaal"),
                    new Seat(528, 3, "528", "2", "Normaal"),
                    new Seat(529, 3, "529", "2", "Normaal"),
                    new Seat(530, 3, "530", "2", "Normaal"),
                    new Seat(531, 3, "531", "2", "Normaal"),
                    new Seat(532, 3, "532", "1", "Normaal"),
                    new Seat(533, 3, "533", "1", "Normaal"),
                    new Seat(534, 3, "534", "1", "Normaal"),
                    new Seat(535, 3, "535", "1", "Normaal"),
                    new Seat(536, 3, "536", "1", "Normaal"),
                    new Seat(537, 3, "537", " ", " "),
                    new Seat(538, 3, "538", " ", " "),
                    new Seat(539, 3, "539", " ", " "),
                    new Seat(540, 3, "540", " ", " "),
                    new Seat(541, 3, "541", " ", " "),
                    new Seat(542, 3, "542", " ", " "),
                    new Seat(543, 3, "543", "1", "Normaal"),
                    new Seat(544, 3, "544", "1", "Normaal"),
                    new Seat(545, 3, "545", "1", "Normaal"),
                    new Seat(546, 3, "546", "1", "Normaal"),
                    new Seat(547, 3, "547", "1", "Normaal"),
                    new Seat(548, 3, "548", "1", "Normaal"),
                    new Seat(549, 3, "549", "2", "Normaal"),
                    new Seat(550, 3, "550", "2", "Normaal"),
                    new Seat(551, 3, "551", "2", "Normaal"),
                    new Seat(552, 3, "552", "2", "Normaal"),
                    new Seat(553, 3, "553", "2", "Normaal"),
                    new Seat(554, 3, "554", "2", "Normaal"),
                    new Seat(555, 3, "555", "2", "Normaal"),
                    new Seat(556, 3, "556", "2", "Normaal"),
                    new Seat(557, 3, "557", "2", "Normaal"),
                    new Seat(558, 3, "558", "2", "Normaal"),
                    new Seat(559, 3, "559", "2", "Normaal"),
                    new Seat(560, 3, "560", "2", "Normaal"),
                    new Seat(561, 3, "561", "1", "Normaal"),
                    new Seat(562, 3, "562", "1", "Normaal"),
                    new Seat(563, 3, "563", "1", "Normaal"),
                    new Seat(564, 3, "564", "1", "Normaal"),
                    new Seat(565, 3, "565", "1", "Normaal"),
                    new Seat(566, 3, "566", "1", "Normaal"),
                    new Seat(567, 3, "567", " ", " "),
                    new Seat(568, 3, "568", " ", " "),
                    new Seat(569, 3, "569", " ", " "),
                    new Seat(570, 3, "570", " ", " "),
                    new Seat(571, 3, "571", " ", " "),
                    new Seat(572, 3, "572", " ", " "),
                    new Seat(573, 3, "573", " ", " "),
                    new Seat(574, 3, "574", "1", "Normaal"),
                    new Seat(575, 3, "575", "1", "Normaal"),
                    new Seat(576, 3, "576", "1", "Normaal"),
                    new Seat(577, 3, "577", "1", "Normaal"),
                    new Seat(578, 3, "578", "1", "Normaal"),
                    new Seat(579, 3, "579", "1", "Normaal"),
                    new Seat(580, 3, "580", "1", "Normaal"),
                    new Seat(581, 3, "581", "1", "Normaal"),
                    new Seat(582, 3, "582", "1", "Normaal"),
                    new Seat(583, 3, "583", "1", "Normaal"),
                    new Seat(584, 3, "584", "1", "Normaal"),
                    new Seat(585, 3, "585", "1", "Normaal"),
                    new Seat(586, 3, "586", "1", "Normaal"),
                    new Seat(587, 3, "587", "1", "Normaal"),
                    new Seat(588, 3, "588", "1", "Normaal"),
                    new Seat(589, 3, "589", "1", "Normaal"),
                    new Seat(590, 3, "590", "1", "Normaal"),
                    new Seat(591, 3, "591", "1", "Normaal"),
                    new Seat(592, 3, "592", "1", "Normaal"),
                    new Seat(593, 3, "593", "1", "Normaal"),
                    new Seat(594, 3, "594", "1", "Normaal"),
                    new Seat(595, 3, "595", "1", "Normaal"),
                    new Seat(596, 3, "596", " ", " "),
                    new Seat(597, 3, "597", " ", " "),
                    new Seat(598, 3, "598", " ", " "),
                    new Seat(599, 3, "599", " ", " ")
                };
                try
                {
                    List<List<Seat>> _layoutList = new List<List<Seat>> { layout1, layout2, layout3 };

                    //Saving to a JSON
                    /*using FileStream createStream = File.Create(@$"{System.IO.Path.GetFullPath(System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"..\..\..\Datasource"))}\Layouts.json");
                    JsonSerializer.SerializeAsync(createStream, _layoutList);
                    Console.WriteLine("✓ Layout json setup!");*/

                    //Saving to DB
                    List<int> RowWidthsLayouts = new List<int> { 12, 18, 30 };
                    foreach (List<Seat> layout in _layoutList) {
                        upload_to_database(layout, new Room(layout[0].RoomID, $"Room{layout[0].RoomID}", layout.Count, RowWidthsLayouts[layout[0].RoomID - 1]));
                    }
                    Console.WriteLine("\n--- 100% ---\nLayout database setup!");
                }
                catch (Exception) { Console.WriteLine("X Layout database setup : Something went wrong!"); }
                finally { sqlite_conn.Close(); }
                Console.ReadLine();
            }
        }

        public static void addSeatToDatabase(int roomID, string name, string rank, string type)
        {
            SQLiteConnection sqlite_conn;
            sqlite_conn = CreateConnection();

            try
            {
                ExcecuteQuerry(sqlite_conn, @$"INSERT INTO Seat( RoomID, Name, Rank, Type ) VALUES (
                    {roomID}, '{name}', '{rank}', '{type}'
                ); ");
                sqlite_conn.Close();
            }
            catch
            {
                sqlite_conn.Close();
            }
        }
        public static void addSeatToDatabase(List<Seat> seats)
        {
            foreach (Seat seat in seats) { addSeatToDatabase(seat.RoomID, seat.Name, seat.Rank, seat.Type); }
        }

        /// <summary>
        /// Create folder if it doesnt exsist
        /// </summary>
        /// <param name="folderName"></param>
        public static void setupFolder(string folderName) => System.IO.Directory.CreateDirectory(System.IO.Path.GetFullPath(System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"..\..\..\" + folderName)));
        private static string databasePath
        {
            get { setupFolder("DataSource"); return System.IO.Path.GetFullPath(System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"..\..\..\DataSource")); }
        }
        /// <summary>
        /// Create database connection
        /// </summary>
        /// <returns>SQLiteConnection object</returns>
        static SQLiteConnection CreateConnection()
        {
            SQLiteConnection sqlite_conn;
            // Create a new database connection:
            sqlite_conn = new SQLiteConnection($"Data Source={databasePath}\\database.db; Version = 3; New = True; Compress = True; ");
            // Open the connection:
            try { sqlite_conn.Open(); }
            catch (Exception) { }
            return sqlite_conn;
        }
        /// <summary>
        /// Create a table by excecuting the querry
        /// </summary>
        /// <param name="conn"></param>
        /// <param name="CreateQuerry"></param>
        /// <exception cref="System.Data.SQLite.SQLiteException"></exception>
        static void ExcecuteQuerry(SQLiteConnection conn, string CreateQuerry)
        {
            SQLiteCommand sqlite_cmd;
            sqlite_cmd = conn.CreateCommand();
            try
            {
                sqlite_cmd.CommandText = CreateQuerry;
                sqlite_cmd.ExecuteNonQuery();
            }
            catch (System.Data.SQLite.SQLiteException)
            {
                throw new System.Data.SQLite.SQLiteException();
            }
        }

        static List<List<string>> ReadData(SQLiteConnection conn)
        {
            SQLiteDataReader sqlite_datareader;
            SQLiteCommand sqlite_cmd;
            sqlite_cmd = conn.CreateCommand();
            sqlite_cmd.CommandText = "SELECT * FROM SampleTable";

            sqlite_datareader = sqlite_cmd.ExecuteReader();
            List<List<string>> toReturn = new List<List<string>> { };
            List<string> temp = new List<string> { };
            while (sqlite_datareader.Read())
            {
                temp.Clear();
                for (int i = 0; i < sqlite_datareader.FieldCount; i++)
                {
                    temp.Add(sqlite_datareader.GetValue(i).ToString() ?? "Not null");
                }
                toReturn.Add(temp);
                //Console.WriteLine();
                //string temp = sqlite_datareader.GetTextReader(0).ReadToEnd();
                //int temp2 = sqlite_datareader.GetInt32(1);
                //Console.WriteLine(temp);
                //Console.WriteLine(temp2);
                //foreach (var item in temp) Console.WriteLine(item);
                /*
                var myreader = sqlite_datareader.GetValues(); //GetString(0);
                foreach (var key in myreader)
                {
                    Console.WriteLine(key);
                    foreach (var item in key.ToString())
                    {
                        Console.WriteLine(item);
                    }
                }*/
            }
            conn.Close();
            return toReturn;
        }
    }
}
